using System;
using Application.Dto;
using AutoMapper;
using Domain.Entities;
using Transversal.Common.Extensions;

namespace Transversal.Mapper
{
    public class MappingProfile:Profile
    {
        public MappingProfile()
        {
            #region Municipalidad
            CreateMap<TM_MUNICIPALIDAD, MunicipalidadDto.RQInsert>()
                .ForMember(destination => destination.sRuc, source => source.MapFrom(src => src.STR_NUMRUC))
                .ForMember(destination => destination.sRazonSocial, source => source.MapFrom(src => src.STR_RAZONSOCIAL))
                .ForMember(destination => destination.nTipoVia, source => source.MapFrom(src => src.NUM_IDTPVIA))
                .ForMember(destination => destination.sVia, source => source.MapFrom(src => src.STR_NOMVIA))
                .ForMember(destination => destination.nCentroPoblado, source => source.MapFrom(src => src.NUM_IDCCPP))
                .ForMember(destination => destination.sCentroPoblado, source => source.MapFrom(src => src.STR_NOMCCPP))
                .ForMember(destination => destination.nIdNumeroManzana, source => source.MapFrom(src => src.NUM_IDNUMAKM))
                .ForMember(destination => destination.sNumeroManzana, source => source.MapFrom(src => src.STR_NUMMZKIL))
                .ForMember(destination => destination.nIdLoteInterior, source => source.MapFrom(src => src.NUM_IDLOINDP))
                .ForMember(destination => destination.sLoteInterior, source => source.MapFrom(src => src.STR_INTLOTE))
                .ForMember(destination => destination.sReferencia, source => source.MapFrom(src => src.STR_REFERENCIA))
                .ForMember(destination => destination.sCodDepartamento, source => source.MapFrom(src => src.STR_CDPTO))
                .ForMember(destination => destination.sCodProvincia, source => source.MapFrom(src => src.STR_CDPROV))
                .ForMember(destination => destination.sCodDistrito, source => source.MapFrom(src => src.STR_CDDIST))
                .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUCREACION))
                .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION))
                .ForMember(destination => destination.sRepresentante, source => source.MapFrom(src => src.STR_REPRESENTANTE))
                .ForMember(destination => destination.nIdentidadsso, source => source.MapFrom(src => src.NUM_IDENTIDADSSO))
                .ForMember(destination => destination.nIdLocalsso, source => source.MapFrom(src => src.NUM_IDLOCALSSO))
                .ReverseMap();
            CreateMap<TM_MUNICIPALIDAD, MunicipalidadDto.RQUpdate>()
                .ForMember(destination => destination.nIdEntidad, source => source.MapFrom(src => src.NUM_IDENTIDAD))
                .ForMember(destination => destination.sRuc, source => source.MapFrom(src => src.STR_NUMRUC))
                .ForMember(destination => destination.sRazonSocial, source => source.MapFrom(src => src.STR_RAZONSOCIAL))
                .ForMember(destination => destination.nTipoVia, source => source.MapFrom(src => src.NUM_IDTPVIA))
                .ForMember(destination => destination.sVia, source => source.MapFrom(src => src.STR_NOMVIA))
                .ForMember(destination => destination.nCentroPoblado, source => source.MapFrom(src => src.NUM_IDCCPP))
                .ForMember(destination => destination.sCentroPoblado, source => source.MapFrom(src => src.STR_NOMCCPP))
                .ForMember(destination => destination.nIdNumeroManzana, source => source.MapFrom(src => src.NUM_IDNUMAKM))
                .ForMember(destination => destination.sNumeroManzana, source => source.MapFrom(src => src.STR_NUMMZKIL))
                .ForMember(destination => destination.nIdLoteInterior, source => source.MapFrom(src => src.NUM_IDLOINDP))
                .ForMember(destination => destination.sLoteInterior, source => source.MapFrom(src => src.STR_INTLOTE))
                .ForMember(destination => destination.sReferencia, source => source.MapFrom(src => src.STR_REFERENCIA))
                .ForMember(destination => destination.sCodDepartamento, source => source.MapFrom(src => src.STR_CDPTO))
                .ForMember(destination => destination.sCodProvincia, source => source.MapFrom(src => src.STR_CDPROV))
                .ForMember(destination => destination.sCodDistrito, source => source.MapFrom(src => src.STR_CDDIST))
                .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUACT))
                .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION))
                .ForMember(destination => destination.sRepresentante, source => source.MapFrom(src => src.STR_REPRESENTANTE))
                .ReverseMap();
            CreateMap<TM_MUNICIPALIDAD, MunicipalidadDto.RQDelete>()
                .ForMember(destination => destination.nIdEntidad, source => source.MapFrom(src => src.NUM_IDENTIDAD))
                .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUACT))
                .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION))
                .ReverseMap();
            CreateMap<TM_MUNICIPALIDAD, MunicipalidadDto.RSGet>()
                .ForMember(destination => destination.nIdEntidad, source => source.MapFrom(src => src.NUM_IDENTIDAD))
                .ForMember(destination => destination.sRuc, source => source.MapFrom(src => src.STR_NUMRUC))
                .ForMember(destination => destination.sRazonSocial, source => source.MapFrom(src => src.STR_RAZONSOCIAL))
                .ForMember(destination => destination.nTipoVia, source => source.MapFrom(src => src.NUM_IDTPVIA))
                .ForMember(destination => destination.sVia, source => source.MapFrom(src => src.STR_NOMVIA))
                .ForMember(destination => destination.nCentroPoblado, source => source.MapFrom(src => src.NUM_IDCCPP))
                .ForMember(destination => destination.sCentroPoblado, source => source.MapFrom(src => src.STR_NOMCCPP))
                .ForMember(destination => destination.nIdNumeroManzana, source => source.MapFrom(src => src.NUM_IDNUMAKM))
                .ForMember(destination => destination.sNumeroManzana, source => source.MapFrom(src => src.STR_NUMMZKIL))
                .ForMember(destination => destination.nIdLoteInterior, source => source.MapFrom(src => src.NUM_IDLOINDP))
                .ForMember(destination => destination.sLoteInterior, source => source.MapFrom(src => src.STR_INTLOTE))
                .ForMember(destination => destination.sReferencia, source => source.MapFrom(src => src.STR_REFERENCIA))
                .ForMember(destination => destination.sCodDepartamento, source => source.MapFrom(src => src.STR_CDPTO))
                .ForMember(destination => destination.sCodProvincia, source => source.MapFrom(src => src.STR_CDPROV))
                .ForMember(destination => destination.sCodDistrito, source => source.MapFrom(src => src.STR_CDDIST))
                .ForMember(destination => destination.sRepresentante, source => source.MapFrom(src => src.STR_REPRESENTANTE))
                .ReverseMap();
            CreateMap<TM_MUNICIPALIDAD, TableModel>()
                .ForMember(destination => destination.Id, source => source.MapFrom(src => src.NUM_IDENTIDAD))
                .ForMember(destination => destination.Column1, source => source.MapFrom(src => src.NUM_FILA))
                .ForMember(destination => destination.Column2, source => source.MapFrom(src => src.STR_NUMRUC))
                .ForMember(destination => destination.Column3, source => source.MapFrom(src => src.STR_RAZONSOCIAL))
                .ForMember(destination => destination.Column4, source => source.MapFrom(src => src.STR_DIRECCION))
                .ReverseMap();
            #endregion

            #region Estacion de Servicio
            CreateMap<TM_ESTACIONSERVICIO, EstacionServicioDto.RQInsert>()
               .ForMember(destination => destination.sRuc, source => source.MapFrom(src => src.STR_NUMRUC))
               .ForMember(destination => destination.sRazonSocial, source => source.MapFrom(src => src.STR_RAZONSOCIAL))
               .ForMember(destination => destination.nTipoVia, source => source.MapFrom(src => src.NUM_IDTPVIA))
               .ForMember(destination => destination.sVia, source => source.MapFrom(src => src.STR_NOMVIA))
               .ForMember(destination => destination.nCentroPoblado, source => source.MapFrom(src => src.NUM_IDCCPP))
               .ForMember(destination => destination.sCentroPoblado, source => source.MapFrom(src => src.STR_NOMCCPP))
               .ForMember(destination => destination.nIdNumeroManzana, source => source.MapFrom(src => src.NUM_IDNUMAKM))
               .ForMember(destination => destination.sNumeroManzana, source => source.MapFrom(src => src.STR_NUMMZKIL))
               .ForMember(destination => destination.nIdLoteInterior, source => source.MapFrom(src => src.NUM_IDLOINDP))
               .ForMember(destination => destination.sLoteInterior, source => source.MapFrom(src => src.STR_INTLOTE))
               .ForMember(destination => destination.sReferencia, source => source.MapFrom(src => src.STR_REFERENCIA))
               .ForMember(destination => destination.sCodDepartamento, source => source.MapFrom(src => src.STR_CDPTO))
               .ForMember(destination => destination.sCodProvincia, source => source.MapFrom(src => src.STR_CDPROV))
               .ForMember(destination => destination.sCodDistrito, source => source.MapFrom(src => src.STR_CDDIST))
               .ForMember(destination => destination.sNroSucursales, source => source.MapFrom(src => src.STR_NROSUCURSALES))
               .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUCREACION))
               .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION))
               .ForMember(destination => destination.sRepresentante, source => source.MapFrom(src => src.STR_REPRESENTANTE))
               .ForMember(destination => destination.nIdentidadsso, source => source.MapFrom(src => src.NUM_IDENTIDADSSO))
               .ForMember(destination => destination.nIdLocalsso, source => source.MapFrom(src => src.NUM_IDLOCALSSO))
               .ReverseMap();
            CreateMap<TM_ESTACIONSERVICIO, EstacionServicioDto.RQUpdate>()
                .ForMember(destination => destination.nIdEstServicio, source => source.MapFrom(src => src.NUM_IDESTSERVICIO))
                .ForMember(destination => destination.sRuc, source => source.MapFrom(src => src.STR_NUMRUC))
                .ForMember(destination => destination.sRazonSocial, source => source.MapFrom(src => src.STR_RAZONSOCIAL))
                .ForMember(destination => destination.nTipoVia, source => source.MapFrom(src => src.NUM_IDTPVIA))
                .ForMember(destination => destination.sVia, source => source.MapFrom(src => src.STR_NOMVIA))
                .ForMember(destination => destination.nCentroPoblado, source => source.MapFrom(src => src.NUM_IDCCPP))
                .ForMember(destination => destination.sCentroPoblado, source => source.MapFrom(src => src.STR_NOMCCPP))
                .ForMember(destination => destination.nIdNumeroManzana, source => source.MapFrom(src => src.NUM_IDNUMAKM))
                .ForMember(destination => destination.sNumeroManzana, source => source.MapFrom(src => src.STR_NUMMZKIL))
                .ForMember(destination => destination.nIdLoteInterior, source => source.MapFrom(src => src.NUM_IDLOINDP))
                .ForMember(destination => destination.sLoteInterior, source => source.MapFrom(src => src.STR_INTLOTE))
                .ForMember(destination => destination.sReferencia, source => source.MapFrom(src => src.STR_REFERENCIA))
                .ForMember(destination => destination.sCodDepartamento, source => source.MapFrom(src => src.STR_CDPTO))
                .ForMember(destination => destination.sCodProvincia, source => source.MapFrom(src => src.STR_CDPROV))
                .ForMember(destination => destination.sCodDistrito, source => source.MapFrom(src => src.STR_CDDIST))
                .ForMember(destination => destination.sNroSucursales, source => source.MapFrom(src => src.STR_NROSUCURSALES))
                .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUACT))
                .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION))
                .ForMember(destination => destination.sRepresentante, source => source.MapFrom(src => src.STR_REPRESENTANTE))
                .ReverseMap();
            CreateMap<TM_ESTACIONSERVICIO, EstacionServicioDto.RQDelete>()
                .ForMember(destination => destination.nIdEstServicio, source => source.MapFrom(src => src.NUM_IDESTSERVICIO))
                .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUACT))
                .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION))
                .ReverseMap();
            CreateMap<TM_ESTACIONSERVICIO, EstacionServicioDto.RSGet>()
                .ForMember(destination => destination.nIdEstServicio, source => source.MapFrom(src => src.NUM_IDESTSERVICIO))
                .ForMember(destination => destination.sRuc, source => source.MapFrom(src => src.STR_NUMRUC))
                .ForMember(destination => destination.sRazonSocial, source => source.MapFrom(src => src.STR_RAZONSOCIAL))
                .ForMember(destination => destination.nTipoVia, source => source.MapFrom(src => src.NUM_IDTPVIA))
                .ForMember(destination => destination.sVia, source => source.MapFrom(src => src.STR_NOMVIA))
                .ForMember(destination => destination.nCentroPoblado, source => source.MapFrom(src => src.NUM_IDCCPP))
                .ForMember(destination => destination.sCentroPoblado, source => source.MapFrom(src => src.STR_NOMCCPP))
                .ForMember(destination => destination.nIdNumeroManzana, source => source.MapFrom(src => src.NUM_IDNUMAKM))
                .ForMember(destination => destination.sNumeroManzana, source => source.MapFrom(src => src.STR_NUMMZKIL))
                .ForMember(destination => destination.nIdLoteInterior, source => source.MapFrom(src => src.NUM_IDLOINDP))
                .ForMember(destination => destination.sLoteInterior, source => source.MapFrom(src => src.STR_INTLOTE))
                .ForMember(destination => destination.sReferencia, source => source.MapFrom(src => src.STR_REFERENCIA))
                .ForMember(destination => destination.sCodDepartamento, source => source.MapFrom(src => src.STR_CDPTO))
                .ForMember(destination => destination.sCodProvincia, source => source.MapFrom(src => src.STR_CDPROV))
                .ForMember(destination => destination.sCodDistrito, source => source.MapFrom(src => src.STR_CDDIST))
                .ForMember(destination => destination.sNroSucursales, source => source.MapFrom(src => src.STR_NROSUCURSALES))
                .ForMember(destination => destination.sRepresentante, source => source.MapFrom(src => src.STR_REPRESENTANTE))
                .ReverseMap();
            CreateMap<TM_ESTACIONSERVICIO, TableModel>()
                .ForMember(destination => destination.Id, source => source.MapFrom(src => src.NUM_IDESTSERVICIO))
                .ForMember(destination => destination.Column1, source => source.MapFrom(src => src.NUM_FILA))
                .ForMember(destination => destination.Column2, source => source.MapFrom(src => src.STR_NUMRUC))
                .ForMember(destination => destination.Column3, source => source.MapFrom(src => src.STR_RAZONSOCIAL))
                .ForMember(destination => destination.Column4, source => source.MapFrom(src => src.STR_DIRECCION))
                .ReverseMap();
            CreateMap<TM_ESTACIONSERVICIO, ComboModelDto.XId>()
                .ForMember(destination => destination.nId, source => source.MapFrom(src => src.NUM_IDESTSERVICIO))
                .ForMember(destination => destination.sDescription, source => source.MapFrom(src => $"{src.STR_NUMRUC}-{src.STR_RAZONSOCIAL}"))
                .ReverseMap();
            #endregion

            #region Contrato de Estacion de Servicio
            CreateMap<TM_CONTRATOES, ContratoEsDto.RQInsert>()
               .ForMember(destination => destination.nIdEstServicio, source => source.MapFrom(src => src.NUM_IDESTSERVICIO))
               .ForMember(destination => destination.nIdEntidad, source => source.MapFrom(src => src.NUM_IDENTIDAD))
               .ForMember(destination => destination.sNumContrato, source => source.MapFrom(src => src.STR_NUMCONTRATO))
               .ForMember(destination => destination.dFecContrato, source => source.MapFrom(src => src.DTE_FECCONTRATO.GetSirosDateTime()))
               .ForMember(destination => destination.dFecIniVigencia, source => source.MapFrom(src => src.DTE_FECINIVIG.GetSirosDateTime()))
               .ForMember(destination => destination.dFecFinVigencia, source => source.MapFrom(src => src.DTE_FECVENVIG.GetSirosDateTime()))
               .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUCREACION))
               .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION));
            CreateMap<ContratoEsDto.RQInsert, TM_CONTRATOES>()
               .ForMember(destination => destination.NUM_IDESTSERVICIO, source => source.MapFrom(src => src.nIdEstServicio))
               .ForMember(destination => destination.NUM_IDENTIDAD, source => source.MapFrom(src => src.nIdEntidad))
               .ForMember(destination => destination.STR_NUMCONTRATO, source => source.MapFrom(src => src.sNumContrato))
               .ForMember(destination => destination.DTE_FECCONTRATO, source => source.MapFrom(src => src.dFecContrato.GetSirosDateString()))
               .ForMember(destination => destination.DTE_FECINIVIG, source => source.MapFrom(src => src.dFecIniVigencia.GetSirosDateString()))
               .ForMember(destination => destination.DTE_FECVENVIG, source => source.MapFrom(src => src.dFecFinVigencia.GetSirosDateString()))
               .ForMember(destination => destination.STR_USUCREACION, source => source.MapFrom(src => src.sUsuario))
               .ForMember(destination => destination.NUM_IDSESION, source => source.MapFrom(src => src.nIdSession));
            CreateMap<TM_CONTRATOES, ContratoEsDto.RQUpdate>()
                .ForMember(destination => destination.nIdEstServicioEnt, source => source.MapFrom(src => src.NUM_IDESTSERVICIOXENT))
                .ForMember(destination => destination.sNumContrato, source => source.MapFrom(src => src.STR_NUMCONTRATO))
                .ForMember(destination => destination.dFecContrato, source => source.MapFrom(src => src.DTE_FECCONTRATO.GetSirosDateTime()))
                .ForMember(destination => destination.dFecIniVigencia, source => source.MapFrom(src => src.DTE_FECINIVIG.GetSirosDateTime()))
                .ForMember(destination => destination.dFecFinVigencia, source => source.MapFrom(src => src.DTE_FECVENVIG.GetSirosDateTime()))
                .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUACT))
                .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION));
            CreateMap<ContratoEsDto.RQUpdate, TM_CONTRATOES>()
               .ForMember(destination => destination.NUM_IDESTSERVICIOXENT, source => source.MapFrom(src => src.nIdEstServicioEnt))
               .ForMember(destination => destination.STR_NUMCONTRATO, source => source.MapFrom(src => src.sNumContrato))
               .ForMember(destination => destination.DTE_FECCONTRATO, source => source.MapFrom(src => src.dFecContrato.GetSirosDateString()))
               .ForMember(destination => destination.DTE_FECINIVIG, source => source.MapFrom(src => src.dFecIniVigencia.GetSirosDateString()))
               .ForMember(destination => destination.DTE_FECVENVIG, source => source.MapFrom(src => src.dFecFinVigencia.GetSirosDateString()))
               .ForMember(destination => destination.STR_USUACT, source => source.MapFrom(src => src.sUsuario))
               .ForMember(destination => destination.NUM_IDSESION, source => source.MapFrom(src => src.nIdSession));
            CreateMap<TM_CONTRATOES, ContratoEsDto.RQDelete>()
                .ForMember(destination => destination.nIdEstServicioEnt, source => source.MapFrom(src => src.NUM_IDESTSERVICIOXENT))
                .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION))
                .ReverseMap();
            CreateMap<TM_CONTRATOES, ContratoEsDto.RSGet>()
                .ForMember(destination => destination.nIdEstServicioEnt, source => source.MapFrom(src => src.NUM_IDESTSERVICIOXENT))
                .ForMember(destination => destination.nIdEstServicio, source => source.MapFrom(src => src.NUM_IDESTSERVICIO))
                .ForMember(destination => destination.nIdEntidad, source => source.MapFrom(src => src.NUM_IDENTIDAD))
                .ForMember(destination => destination.sNumContrato, source => source.MapFrom(src => src.STR_NUMCONTRATO))
                .ForMember(destination => destination.dFecContrato, source => source.MapFrom(src => src.DTE_FECCONTRATO))
                .ForMember(destination => destination.dFecIniVigencia, source => source.MapFrom(src => src.DTE_FECINIVIG))
                .ForMember(destination => destination.dFecFinVigencia, source => source.MapFrom(src => src.DTE_FECVENVIG))
                .ReverseMap();
            CreateMap<TM_CONTRATOES, TableModel>()
                .ForMember(destination => destination.Id, source => source.MapFrom(src => src.NUM_IDESTSERVICIOXENT))
                .ForMember(destination => destination.Column1, source => source.MapFrom(src => src.NUM_FILA))
                .ForMember(destination => destination.Column2, source => source.MapFrom(src => src.STR_NUMRUC))
                .ForMember(destination => destination.Column3, source => source.MapFrom(src => src.STR_RAZONSOCIAL))
                .ForMember(destination => destination.Column4, source => source.MapFrom(src => src.STR_NUMCONTRATO))
                .ForMember(destination => destination.Column5, source => source.MapFrom(src => src.DTE_FECCONTRATO))
                .ReverseMap();
            #endregion

            #region Combustible

            CreateMap<TM_COMBUSTIBLE, CombustibleDto.RSGet>()
                .ForMember(destination => destination.nIdCombustible, source => source.MapFrom(src => src.NUM_IDCOMBUSTIBLE))
                .ForMember(destination => destination.sDsCombustible, source => source.MapFrom(src => src.STR_DSCOMBUSTIBLE))
                .ReverseMap();
            CreateMap<TM_COMBUSTIBLE, TableModel>()
                .ForMember(destination => destination.Id, source => source.MapFrom(src => src.NUM_IDCOMBUSTIBLE))
                .ForMember(destination => destination.Column1, source => source.MapFrom(src => src.NUM_IDCOMBUSTIBLE))
                .ForMember(destination => destination.Column2, source => source.MapFrom(src => src.STR_DSCOMBUSTIBLE))
                .ReverseMap();
            #endregion

            #region Rutas

            CreateMap<TM_RUTA, RutaDto.RSGet>()
                .ForMember(destination => destination.nIdRuta, source => source.MapFrom(src => src.NUM_IDRUTA))
                .ForMember(destination => destination.sNroRuta, source => source.MapFrom(src => src.STR_NRORUTA))
                .ForMember(destination => destination.sNombreRuta, source => source.MapFrom(src => src.STR_NOMBRERUTA))
                .ForMember(destination => destination.sItinerario, source => source.MapFrom(src => src.STR_ITINERARIO))
                .ForMember(destination => destination.sKilometro, source => source.MapFrom(src => src.STR_KILOMETRO))
                .ReverseMap();
            CreateMap<TM_RUTA, TableModel>()
                .ForMember(destination => destination.Id, source => source.MapFrom(src => src.NUM_IDRUTA))
                .ForMember(destination => destination.Column1, source => source.MapFrom(src => src.NUM_IDRUTA))
                .ForMember(destination => destination.Column2, source => source.MapFrom(src => src.STR_NRORUTA))
                .ForMember(destination => destination.Column3, source => source.MapFrom(src => src.STR_NOMBRERUTA))
                .ForMember(destination => destination.Column4, source => source.MapFrom(src => src.STR_ITINERARIO))
                .ForMember(destination => destination.Column5, source => source.MapFrom(src => src.STR_KILOMETRO))
                .ReverseMap();

            #endregion

            #region Sucursal Estacion de Servicio
            CreateMap<TM_SUCURSAL_ES, SucursalESDto.RQInsert>()
              .ForMember(destination => destination.nIdEstServicio, source => source.MapFrom(src => src.NUM_IDESTSERVICIO))
              .ForMember(destination => destination.nTipoVia, source => source.MapFrom(src => src.NUM_IDTPVIA))
              .ForMember(destination => destination.sVia, source => source.MapFrom(src => src.STR_NOMVIA))
              .ForMember(destination => destination.nCentroPoblado, source => source.MapFrom(src => src.NUM_IDCCPP))
              .ForMember(destination => destination.sCentroPoblado, source => source.MapFrom(src => src.STR_NOMCCPP))
              .ForMember(destination => destination.nIdNumeroManzana, source => source.MapFrom(src => src.NUM_IDNUMAKM))
              .ForMember(destination => destination.sNumeroManzana, source => source.MapFrom(src => src.STR_NUMMZKIL))
              .ForMember(destination => destination.nIdLoteInterior, source => source.MapFrom(src => src.NUM_IDLOINDP))
              .ForMember(destination => destination.sLoteInterior, source => source.MapFrom(src => src.STR_INTLOTE))
              .ForMember(destination => destination.sReferencia, source => source.MapFrom(src => src.STR_REFERENCIA))
              .ForMember(destination => destination.sCodDepartamento, source => source.MapFrom(src => src.STR_CDPTO))
              .ForMember(destination => destination.sCodProvincia, source => source.MapFrom(src => src.STR_CDPROV))
              .ForMember(destination => destination.sCodDistrito, source => source.MapFrom(src => src.STR_CDDIST))
              .ForMember(destination => destination.sLatitud, source => source.MapFrom(src => src.STR_LATITUD))
              .ForMember(destination => destination.sLongitud, source => source.MapFrom(src => src.STR_LONGITUD))
              .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUCREACION))
              .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION))
              .ForMember(destination => destination.nIdentidadUsuario, source => source.MapFrom(src => src.NUM_IDENTIDADUSUARIO))
              .ForMember(destination => destination.nIdentidadsso, source => source.MapFrom(src => src.NUM_IDENTIDADSSO))
              .ForMember(destination => destination.nIdLocalsso, source => source.MapFrom(src => src.NUM_IDLOCALSSO))
              .ReverseMap();
            CreateMap<TM_SUCURSAL_ES, SucursalESDto.RQUpdate>()
              .ForMember(destination => destination.nIdSucursalxES, source => source.MapFrom(src => src.NUM_IDSUCURSALXES))
              .ForMember(destination => destination.nTipoVia, source => source.MapFrom(src => src.NUM_IDTPVIA))
              .ForMember(destination => destination.sVia, source => source.MapFrom(src => src.STR_NOMVIA))
              .ForMember(destination => destination.nCentroPoblado, source => source.MapFrom(src => src.NUM_IDCCPP))
              .ForMember(destination => destination.sCentroPoblado, source => source.MapFrom(src => src.STR_NOMCCPP))
              .ForMember(destination => destination.nIdNumeroManzana, source => source.MapFrom(src => src.NUM_IDNUMAKM))
              .ForMember(destination => destination.sNumeroManzana, source => source.MapFrom(src => src.STR_NUMMZKIL))
              .ForMember(destination => destination.nIdLoteInterior, source => source.MapFrom(src => src.NUM_IDLOINDP))
              .ForMember(destination => destination.sLoteInterior, source => source.MapFrom(src => src.STR_INTLOTE))
              .ForMember(destination => destination.sReferencia, source => source.MapFrom(src => src.STR_REFERENCIA))
              .ForMember(destination => destination.sCodDepartamento, source => source.MapFrom(src => src.STR_CDPTO))
              .ForMember(destination => destination.sCodProvincia, source => source.MapFrom(src => src.STR_CDPROV))
              .ForMember(destination => destination.sCodDistrito, source => source.MapFrom(src => src.STR_CDDIST))
              .ForMember(destination => destination.sLatitud, source => source.MapFrom(src => src.STR_LATITUD))
              .ForMember(destination => destination.sLongitud, source => source.MapFrom(src => src.STR_LONGITUD))
              .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUACT))
              .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION))
                .ReverseMap();
            CreateMap<TM_SUCURSAL_ES, SucursalESDto.RQDelete>()
                .ForMember(destination => destination.nIdSucursalxES, source => source.MapFrom(src => src.NUM_IDSUCURSALXES))
                .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUACT))
                .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION))
                .ReverseMap();
            CreateMap<TM_SUCURSAL_ES, SucursalESDto.RSGet>()
                .ForMember(destination => destination.nIdSucursalxES, source => source.MapFrom(src => src.NUM_IDSUCURSALXES))
                .ForMember(destination => destination.nIdEstServicio, source => source.MapFrom(src => src.NUM_IDESTSERVICIO))
                .ForMember(destination => destination.nTipoVia, source => source.MapFrom(src => src.NUM_IDTPVIA))
                .ForMember(destination => destination.sVia, source => source.MapFrom(src => src.STR_NOMVIA))
                .ForMember(destination => destination.nCentroPoblado, source => source.MapFrom(src => src.NUM_IDCCPP))
                .ForMember(destination => destination.sCentroPoblado, source => source.MapFrom(src => src.STR_NOMCCPP))
                .ForMember(destination => destination.nIdNumeroManzana, source => source.MapFrom(src => src.NUM_IDNUMAKM))
                .ForMember(destination => destination.sNumeroManzana, source => source.MapFrom(src => src.STR_NUMMZKIL))
                .ForMember(destination => destination.nIdLoteInterior, source => source.MapFrom(src => src.NUM_IDLOINDP))
                .ForMember(destination => destination.sLoteInterior, source => source.MapFrom(src => src.STR_INTLOTE))
                .ForMember(destination => destination.sReferencia, source => source.MapFrom(src => src.STR_REFERENCIA))
                .ForMember(destination => destination.sCodDepartamento, source => source.MapFrom(src => src.STR_CDPTO))
                .ForMember(destination => destination.sCodProvincia, source => source.MapFrom(src => src.STR_CDPROV))
                .ForMember(destination => destination.sCodDistrito, source => source.MapFrom(src => src.STR_CDDIST))
                .ForMember(destination => destination.sLatitud, source => source.MapFrom(src => src.STR_LATITUD))
                .ForMember(destination => destination.sLongitud, source => source.MapFrom(src => src.STR_LONGITUD))
                .ReverseMap();
            CreateMap<TM_SUCURSAL_ES, TableModel>()
                .ForMember(destination => destination.Id, source => source.MapFrom(src => src.NUM_IDSUCURSALXES))
                .ForMember(destination => destination.Column1, source => source.MapFrom(src => src.NUM_FILA))
                .ForMember(destination => destination.Column2, source => source.MapFrom(src => src.STR_NUMRUC))
                .ForMember(destination => destination.Column3, source => source.MapFrom(src => src.STR_RAZONSOCIAL))
                .ForMember(destination => destination.Column4, source => source.MapFrom(src => src.STR_DIRECCION))
                .ReverseMap();
            #endregion

            #region Operador de Sucursal de estacion de servicio
            CreateMap<TM_OPERADOR_ES, OperadorESDto.RQInsert>()
              .ForMember(destination => destination.nIdSucursalxES, source => source.MapFrom(src => src.NUM_IDSUCURSALXES))
              .ForMember(destination => destination.nIdTpDocumento, source => source.MapFrom(src => src.NUM_IDTPDOCUMENTO))
              .ForMember(destination => destination.sNroDocumento, source => source.MapFrom(src => src.STR_NUMDOCUMENTO))
              .ForMember(destination => destination.sApePaterno, source => source.MapFrom(src => src.STR_APEPATERNO))
              .ForMember(destination => destination.sApeMaterno, source => source.MapFrom(src => src.STR_APEMATERNO))
              .ForMember(destination => destination.sNombre, source => source.MapFrom(src => src.STR_NOMBRE))
              .ForMember(destination => destination.nIdTipoOper, source => source.MapFrom(src => src.NUM_IDTIPOOPER))
              .ForMember(destination => destination.sFecNacimiento, source => source.MapFrom(src => src.DTE_FECNACIMIENTO))
              .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUCREACION))
              .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION))
              .ReverseMap();
            CreateMap<TM_OPERADOR_ES, OperadorESDto.RQUpdate>()
                .ForMember(destination => destination.nIdNominaXSucursal, source => source.MapFrom(src => src.NUM_IDNOMINAXSUCURSAL))
                .ForMember(destination => destination.nIdTipoOper, source => source.MapFrom(src => src.NUM_IDTIPOOPER))
                .ForMember(destination => destination.sFecNacimiento, source => source.MapFrom(src => src.DTE_FECNACIMIENTO))
                .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUCREACION))
                .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION))
                .ReverseMap();
            CreateMap<TM_OPERADOR_ES, OperadorESDto.RQDelete>()
                .ForMember(destination => destination.nIdNominaXSucursal, source => source.MapFrom(src => src.NUM_IDNOMINAXSUCURSAL))
                .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUACT))
                .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION))
                .ReverseMap();
            CreateMap<TM_OPERADOR_ES, OperadorESDto.RSGet>()
                .ForMember(destination => destination.nIdNominaXSucursal, source => source.MapFrom(src => src.NUM_IDNOMINAXSUCURSAL))
                .ForMember(destination => destination.nIdSucursalxES, source => source.MapFrom(src => src.NUM_IDSUCURSALXES))
                .ForMember(destination => destination.nIdTpDocumento, source => source.MapFrom(src => src.NUM_IDTPDOCUMENTO))
                .ForMember(destination => destination.sNroDocumento, source => source.MapFrom(src => src.STR_NUMDOCUMENTO))
                .ForMember(destination => destination.sApePaterno, source => source.MapFrom(src => src.STR_APEPATERNO))
                .ForMember(destination => destination.sApeMaterno, source => source.MapFrom(src => src.STR_APEMATERNO))
                .ForMember(destination => destination.sNombre, source => source.MapFrom(src => src.STR_NOMBRE))
                .ForMember(destination => destination.nIdTipoOper, source => source.MapFrom(src => src.NUM_IDTIPOOPER))
                .ForMember(destination => destination.sFecNacimiento, source => source.MapFrom(src => src.DTE_FECNACIMIENTO.ToAppSirosDate()))
                .ReverseMap();
            CreateMap<TM_OPERADOR_ES, TableModel>()
                .ForMember(destination => destination.Id, source => source.MapFrom(src => src.NUM_IDNOMINAXSUCURSAL))
                .ForMember(destination => destination.Column1, source => source.MapFrom(src => src.NUM_FILA))
                .ForMember(destination => destination.Column2, source => source.MapFrom(src => src.STR_NUMDOCUMENTO))
                .ForMember(destination => destination.Column3, source => source.MapFrom(src => $"{src.STR_NOMBRE} {src.STR_APEPATERNO} {src.STR_APEMATERNO}"))
                .ForMember(destination => destination.Column4, source => source.MapFrom(src => src.STR_DSTIPOOPER))
                .ReverseMap();
            #endregion

            #region Empresa

            CreateMap<TM_EMPRESA, EmpresaDto.RQInsert>()
                .ForMember(destination => destination.sRuc, source => source.MapFrom(src => src.STR_NUMRUC))
                .ForMember(destination => destination.sRazonSocial, source => source.MapFrom(src => src.STR_RAZONSOCIAL))
                .ForMember(destination => destination.nIdTipoVia, source => source.MapFrom(src => src.NUM_IDTPVIA))
                .ForMember(destination => destination.sNombreVia, source => source.MapFrom(src => src.STR_NOMVIA))
                .ForMember(destination => destination.nIdCcpp, source => source.MapFrom(src => src.NUM_IDCCPP))
                .ForMember(destination => destination.sNombreCcpp, source => source.MapFrom(src => src.STR_NOMCCPP))
                .ForMember(destination => destination.nIdNroMzKm, source => source.MapFrom(src => src.NUM_IDNUMAKM))
                .ForMember(destination => destination.sNroMzKm, source => source.MapFrom(src => src.STR_NUMMZKIL))
                .ForMember(destination => destination.nIdLoteIntDpto, source => source.MapFrom(src => src.NUM_IDLOINDP))
                .ForMember(destination => destination.sLoteIntDpto, source => source.MapFrom(src => src.STR_INTLOTE))
                .ForMember(destination => destination.sReferencia, source => source.MapFrom(src => src.STR_REFERENCIA))
                .ForMember(destination => destination.sCodDistrito, source => source.MapFrom(src => src.STR_CDDIST))
                .ForMember(destination => destination.sCodProvincia, source => source.MapFrom(src => src.STR_CDPROV))
                .ForMember(destination => destination.sCodDepartamento, source => source.MapFrom(src => src.STR_CDPTO))
                .ForMember(destination => destination.sTelefono, source => source.MapFrom(src => src.STR_TELEFONO))
                .ForMember(destination => destination.sRepresentante, source => source.MapFrom(src => src.STR_REPRESENTANTE))
                .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUCREACION))
                .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION))
                .ForMember(destination => destination.nIdEntidadSSO, source => source.MapFrom(src => src.NUM_IDENTIDAD))
                .ReverseMap();
            CreateMap<TM_EMPRESA, EmpresaDto.RQUpdate>()
                .ForMember(destination => destination.nIdEmpresa, source => source.MapFrom(src => src.NUM_IDEMPRESA))
                .ForMember(destination => destination.sRuc, source => source.MapFrom(src => src.STR_NUMRUC))
                .ForMember(destination => destination.sRazonSocial, source => source.MapFrom(src => src.STR_RAZONSOCIAL))
                .ForMember(destination => destination.nIdTipoVia, source => source.MapFrom(src => src.NUM_IDTPVIA))
                .ForMember(destination => destination.sNombreVia, source => source.MapFrom(src => src.STR_NOMVIA))
                .ForMember(destination => destination.nIdCcpp, source => source.MapFrom(src => src.NUM_IDCCPP))
                .ForMember(destination => destination.sNombreCcpp, source => source.MapFrom(src => src.STR_NOMCCPP))
                .ForMember(destination => destination.nIdNroMzKm, source => source.MapFrom(src => src.NUM_IDNUMAKM))
                .ForMember(destination => destination.sNroMzKm, source => source.MapFrom(src => src.STR_NUMMZKIL))
                .ForMember(destination => destination.nIdLoteIntDpto, source => source.MapFrom(src => src.NUM_IDLOINDP))
                .ForMember(destination => destination.sLoteIntDpto, source => source.MapFrom(src => src.STR_INTLOTE))
                .ForMember(destination => destination.sReferencia, source => source.MapFrom(src => src.STR_REFERENCIA))
                .ForMember(destination => destination.sCodDistrito, source => source.MapFrom(src => src.STR_CDDIST))
                .ForMember(destination => destination.sCodProvincia, source => source.MapFrom(src => src.STR_CDPROV))
                .ForMember(destination => destination.sCodDepartamento, source => source.MapFrom(src => src.STR_CDPTO))
                .ForMember(destination => destination.sTelefono, source => source.MapFrom(src => src.STR_TELEFONO))
                .ForMember(destination => destination.sRepresentante, source => source.MapFrom(src => src.STR_REPRESENTANTE))
                .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUACT))
                .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION))
                .ForMember(destination => destination.nIdEntidadSSO, source => source.MapFrom(src => src.NUM_IDENTIDAD))
                .ReverseMap();
            CreateMap<TM_EMPRESA, EmpresaDto.RQDelete>()
                .ForMember(destination => destination.nIdEmpresa, source => source.MapFrom(src => src.NUM_IDEMPRESA))
                .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUACT))
                .ForMember(destination => destination.nIdSession, source => source.MapFrom(src => src.NUM_IDSESION))
                .ForMember(destination => destination.nIdEntidadSSO, source => source.MapFrom(src => src.NUM_IDENTIDAD))
                .ReverseMap();
            CreateMap<TM_EMPRESA, EmpresaDto.RSGet>()
                .ForMember(destination => destination.nIdEmpresa, source => source.MapFrom(src => src.NUM_IDEMPRESA))
                .ForMember(destination => destination.sRuc, source => source.MapFrom(src => src.STR_NUMRUC))
                .ForMember(destination => destination.sRazonSocial, source => source.MapFrom(src => src.STR_RAZONSOCIAL))
                .ForMember(destination => destination.nIdTipoVia, source => source.MapFrom(src => src.NUM_IDTPVIA))
                .ForMember(destination => destination.sNombreVia, source => source.MapFrom(src => src.STR_NOMVIA))
                .ForMember(destination => destination.nIdCcpp, source => source.MapFrom(src => src.NUM_IDCCPP))
                .ForMember(destination => destination.sNombreCcpp, source => source.MapFrom(src => src.STR_NOMCCPP))
                .ForMember(destination => destination.nIdNroMzKm, source => source.MapFrom(src => src.NUM_IDNUMAKM))
                .ForMember(destination => destination.sNroMzKm, source => source.MapFrom(src => src.STR_NUMMZKIL))
                .ForMember(destination => destination.nIdLoteIntDpto, source => source.MapFrom(src => src.NUM_IDLOINDP))
                .ForMember(destination => destination.sLoteIntDpto, source => source.MapFrom(src => src.STR_INTLOTE))
                .ForMember(destination => destination.sReferencia, source => source.MapFrom(src => src.STR_REFERENCIA))
                .ForMember(destination => destination.sCodDistrito, source => source.MapFrom(src => src.STR_CDDIST))
                .ForMember(destination => destination.sCodProvincia, source => source.MapFrom(src => src.STR_CDPROV))
                .ForMember(destination => destination.sCodDepartamento, source => source.MapFrom(src => src.STR_CDPTO))
                .ForMember(destination => destination.sTelefono, source => source.MapFrom(src => src.STR_TELEFONO))
                .ForMember(destination => destination.sRepresentante, source => source.MapFrom(src => src.STR_REPRESENTANTE))
                .ReverseMap();
            CreateMap<TM_EMPRESA, TableModel>()
                .ForMember(destination => destination.Id, source => source.MapFrom(src => src.NUM_IDEMPRESA))
                .ForMember(destination => destination.Column1, source => source.MapFrom(src => src.NUM_FILA))
                .ForMember(destination => destination.Column2, source => source.MapFrom(src => src.STR_NUMRUC))
                .ForMember(destination => destination.Column3, source => source.MapFrom(src => src.STR_RAZONSOCIAL))
                .ForMember(destination => destination.Column4, source => source.MapFrom(src => src.STR_DIRECCION))
                .ForMember(destination => destination.Column5, source => source.MapFrom(src => src.STR_TELEFONO))
                .ReverseMap();

            #endregion

            #region General
            CreateMap<GENERAL.TIPO_VIA, ComboModelDto.XId>()
                .ForMember(destination => destination.nId, source => source.MapFrom(src => src.NUM_IDTPVIA))
                .ForMember(destination => destination.sDescription, source => source.MapFrom(src => src.STR_DSTPVIA))
                .ReverseMap();
            CreateMap<GENERAL.CENTRO_POBLADO, ComboModelDto.XId>()
                .ForMember(destination => destination.nId, source => source.MapFrom(src => src.NUM_IDCCPP))
                .ForMember(destination => destination.sDescription, source => source.MapFrom(src => src.STR_DSCCPP))
                .ReverseMap();
            CreateMap<GENERAL.NUMERO_MANZANA, ComboModelDto.XId>()
                .ForMember(destination => destination.nId, source => source.MapFrom(src => src.NUM_IDNUMAKM))
                .ForMember(destination => destination.sDescription, source => source.MapFrom(src => src.STR_DSNUMAKM))
                .ReverseMap();
            CreateMap<GENERAL.LOTE_INTERIOR, ComboModelDto.XId>()
                .ForMember(destination => destination.nId, source => source.MapFrom(src => src.NUM_IDLOINDP))
                .ForMember(destination => destination.sDescription, source => source.MapFrom(src => src.STR_DSLOINDP))
                .ReverseMap();
            CreateMap<GENERAL.DEPARTAMENTO, ComboModelDto.XCodigo>()
                .ForMember(destination => destination.sCodigo, source => source.MapFrom(src => src.STR_CDPTO))
                .ForMember(destination => destination.sDescription, source => source.MapFrom(src => src.STR_DSDPTO))
                .ReverseMap();
            CreateMap<GENERAL.PROVINCIA, ComboModelDto.XCodigo>()
               .ForMember(destination => destination.sCodigo, source => source.MapFrom(src => src.STR_CDPROV))
               .ForMember(destination => destination.sDescription, source => source.MapFrom(src => src.STR_DSPROV))
               .ReverseMap();
            CreateMap<GENERAL.DISTRITO, ComboModelDto.XCodigo>()
               .ForMember(destination => destination.sCodigo, source => source.MapFrom(src => src.STR_CDDIST))
               .ForMember(destination => destination.sDescription, source => source.MapFrom(src => src.STR_DSDIST))
               .ReverseMap();
            CreateMap<GENERAL.TIPO_DOCUMENTO_REPRESENTANTELEGAL, ComboModelDto.XId>()
               .ForMember(destination => destination.nId, source => source.MapFrom(src => src.NUM_IDTPDOCUMENTO))
               .ForMember(destination => destination.sDescription, source => source.MapFrom(src => src.STR_DSTPDOCUMENTO))
               .ReverseMap();
            CreateMap<GENERAL.CARGO_REPRESENTANTELEGAL, ComboModelDto.XId>()
               .ForMember(destination => destination.nId, source => source.MapFrom(src => src.NUM_IDCARGO))
               .ForMember(destination => destination.sDescription, source => source.MapFrom(src => src.STR_DSCARGO))
               .ReverseMap();
            CreateMap<GENERAL.TIPO_OPERADOR, ComboModelDto.XId>()
               .ForMember(destination => destination.nId, source => source.MapFrom(src => src.NUM_IDTIPOOPER))
               .ForMember(destination => destination.sDescription, source => source.MapFrom(src => src.STR_DSTIPOOPER))
               .ReverseMap();
            #endregion

            #region Admin
            CreateMap<ADMIN.TM_SESION, AdminDto.RegistrarSesion>()
                .ForMember(destination => destination.sUsuario, source => source.MapFrom(src => src.STR_USUARIO))
                .ForMember(destination => destination.sUsuarioSSO, source => source.MapFrom(src => src.STR_USERSO))
                .ForMember(destination => destination.sIp, source => source.MapFrom(src => src.STR_NUMEROIP))
                .ForMember(destination => destination.sFlag, source => source.MapFrom(src => src.STR_FLAGCR))
                .ForMember(destination => destination.nIdSessionSSO, source => source.MapFrom(src => src.NUM_IDSESIONSSO))
                .ReverseMap();
            #endregion
        }
    }
}
