//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsSoapONGEI
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", ConfigurationName="wsSoapONGEI.ServiciosOngeiMTC")]
    public interface ServiciosOngeiMTC
    {
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://mtc.gob.pe/ServiciosOngeiMTC/PCMEnviarSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsSoapONGEI.PCMEnviarSMSResponse> PCMEnviarSMSAsync(wsSoapONGEI.PCMEnviarSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mtc.gob.pe/ServiciosOngeiMTC/MigraciogetCarnetExt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsSoapONGEI.MigraciogetCarnetExtResponse> MigraciogetCarnetExtAsync(wsSoapONGEI.MigraciogetCarnetExtRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://mtc.gob.pe/ServiciosOngeiMTC/PJgetAntecPenales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsSoapONGEI.PJgetAntecPenalesResponse> PJgetAntecPenalesAsync(wsSoapONGEI.PJgetAntecPenalesRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://mtc.gob.pe/ServiciosOngeiMTC/ONPconsultarPensionista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsSoapONGEI.ONPconsultarPensionistaResponse> ONPconsultarPensionistaAsync(wsSoapONGEI.ONPconsultarPensionistaRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://mtc.gob.pe/ServiciosOngeiMTC/SusaludConsulAfiliados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsSoapONGEI.SusaludConsulAfiliadosResponse> SusaludConsulAfiliadosAsync(wsSoapONGEI.SusaludConsulAfiliadosRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://mtc.gob.pe/ServiciosOngeiMTC/ReniecActuaCredencial", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsSoapONGEI.ReniecActuaCredencialResponse> ReniecActuaCredencialAsync(wsSoapONGEI.ReniecActuaCredencialRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://mtc.gob.pe/ServiciosOngeiMTC/ReniecConsultDni", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsSoapONGEI.ReniecConsultDniResponse> ReniecConsultDniAsync(wsSoapONGEI.ReniecConsultDniRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://mtc.gob.pe/ServiciosOngeiMTC/MineduConsulTitulo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsSoapONGEI.MineduConsulTituloResponse> MineduConsulTituloAsync(wsSoapONGEI.MineduConsulTituloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mtc.gob.pe/ServiciosOngeiMTC/InpegetAntecedenteJudicial", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsSoapONGEI.InpegetAntecedenteJudicialResponse> InpegetAntecedenteJudicialAsync(wsSoapONGEI.InpegetAntecedenteJudicialRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://mtc.gob.pe/ServiciosOngeiMTC/SuneduConsulRNGT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsSoapONGEI.SuneduConsulRNGTResponse> SuneduConsulRNGTAsync(wsSoapONGEI.SuneduConsulRNGTRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PCMEnviarSMS", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class PCMEnviarSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("numeros", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] numeros;
        
        public PCMEnviarSMSRequest()
        {
        }
        
        public PCMEnviarSMSRequest(string mensaje, string[] numeros)
        {
            this.mensaje = mensaje;
            this.numeros = numeros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PCMEnviarSMSResponse", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class PCMEnviarSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje;
        
        public PCMEnviarSMSResponse()
        {
        }
        
        public PCMEnviarSMSResponse(string transaccion, string mensaje)
        {
            this.transaccion = transaccion;
            this.mensaje = mensaje;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/")]
    public partial class CarnetExtranjeria
    {
        
        private string calidadMigratoriaField;
        
        private string nombresField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private string numRespuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string calidadMigratoria
        {
            get
            {
                return this.calidadMigratoriaField;
            }
            set
            {
                this.calidadMigratoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombres
        {
            get
            {
                return this.nombresField;
            }
            set
            {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string primerApellido
        {
            get
            {
                return this.primerApellidoField;
            }
            set
            {
                this.primerApellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string segundoApellido
        {
            get
            {
                return this.segundoApellidoField;
            }
            set
            {
                this.segundoApellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numRespuesta
        {
            get
            {
                return this.numRespuestaField;
            }
            set
            {
                this.numRespuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/")]
    public partial class Persona
    {
        
        private string tipoDocumentoField;
        
        private string nroDocumentoField;
        
        private string apellidoPaternoField;
        
        private string apellidoMaternoField;
        
        private string nombresField;
        
        private string abreviaturaTituloField;
        
        private string tituloProfesionalField;
        
        private string universidadField;
        
        private string especialidadField;
        
        private string paisField;
        
        private string tipoInstitucionField;
        
        private string tipoGestionField;
        
        private string fechaEmisionField;
        
        private string resolucionField;
        
        private string fechaResolucionField;
        
        private string tipoGraduacionField;
        
        private string fechaGraduacionField;
        
        private string numeroDiplomaField;
        
        private string numeroLibroField;
        
        private string numeroFolioField;
        
        private string numeroRegistroField;
        
        private string nombreFacultadField;
        
        private string nombreCarreraField;
        
        private string nombreEscuelaField;
        
        private string cargoAutoridad1Field;
        
        private string nombreAutoridad1Field;
        
        private string cargoAutoridad2Field;
        
        private string nombreAutoridad2Field;
        
        private string cargoAutoridad3Field;
        
        private string nombreAutoridad3Field;
        
        private string numeroOficioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tipoDocumento
        {
            get
            {
                return this.tipoDocumentoField;
            }
            set
            {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nroDocumento
        {
            get
            {
                return this.nroDocumentoField;
            }
            set
            {
                this.nroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string apellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string apellidoMaterno
        {
            get
            {
                return this.apellidoMaternoField;
            }
            set
            {
                this.apellidoMaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombres
        {
            get
            {
                return this.nombresField;
            }
            set
            {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string abreviaturaTitulo
        {
            get
            {
                return this.abreviaturaTituloField;
            }
            set
            {
                this.abreviaturaTituloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tituloProfesional
        {
            get
            {
                return this.tituloProfesionalField;
            }
            set
            {
                this.tituloProfesionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string universidad
        {
            get
            {
                return this.universidadField;
            }
            set
            {
                this.universidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string especialidad
        {
            get
            {
                return this.especialidadField;
            }
            set
            {
                this.especialidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string pais
        {
            get
            {
                return this.paisField;
            }
            set
            {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string tipoInstitucion
        {
            get
            {
                return this.tipoInstitucionField;
            }
            set
            {
                this.tipoInstitucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string tipoGestion
        {
            get
            {
                return this.tipoGestionField;
            }
            set
            {
                this.tipoGestionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string fechaEmision
        {
            get
            {
                return this.fechaEmisionField;
            }
            set
            {
                this.fechaEmisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string resolucion
        {
            get
            {
                return this.resolucionField;
            }
            set
            {
                this.resolucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string fechaResolucion
        {
            get
            {
                return this.fechaResolucionField;
            }
            set
            {
                this.fechaResolucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string tipoGraduacion
        {
            get
            {
                return this.tipoGraduacionField;
            }
            set
            {
                this.tipoGraduacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string fechaGraduacion
        {
            get
            {
                return this.fechaGraduacionField;
            }
            set
            {
                this.fechaGraduacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string numeroDiploma
        {
            get
            {
                return this.numeroDiplomaField;
            }
            set
            {
                this.numeroDiplomaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string numeroLibro
        {
            get
            {
                return this.numeroLibroField;
            }
            set
            {
                this.numeroLibroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string numeroFolio
        {
            get
            {
                return this.numeroFolioField;
            }
            set
            {
                this.numeroFolioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string numeroRegistro
        {
            get
            {
                return this.numeroRegistroField;
            }
            set
            {
                this.numeroRegistroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string nombreFacultad
        {
            get
            {
                return this.nombreFacultadField;
            }
            set
            {
                this.nombreFacultadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string nombreCarrera
        {
            get
            {
                return this.nombreCarreraField;
            }
            set
            {
                this.nombreCarreraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string nombreEscuela
        {
            get
            {
                return this.nombreEscuelaField;
            }
            set
            {
                this.nombreEscuelaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string cargoAutoridad1
        {
            get
            {
                return this.cargoAutoridad1Field;
            }
            set
            {
                this.cargoAutoridad1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string nombreAutoridad1
        {
            get
            {
                return this.nombreAutoridad1Field;
            }
            set
            {
                this.nombreAutoridad1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string cargoAutoridad2
        {
            get
            {
                return this.cargoAutoridad2Field;
            }
            set
            {
                this.cargoAutoridad2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string nombreAutoridad2
        {
            get
            {
                return this.nombreAutoridad2Field;
            }
            set
            {
                this.nombreAutoridad2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string cargoAutoridad3
        {
            get
            {
                return this.cargoAutoridad3Field;
            }
            set
            {
                this.cargoAutoridad3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string nombreAutoridad3
        {
            get
            {
                return this.nombreAutoridad3Field;
            }
            set
            {
                this.nombreAutoridad3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string numeroOficio
        {
            get
            {
                return this.numeroOficioField;
            }
            set
            {
                this.numeroOficioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/")]
    public partial class respuesta
    {
        
        private string fechaSuneduField;
        
        private string horaSuneduField;
        
        private string cGenericoField;
        
        private string dGenericaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fechaSunedu
        {
            get
            {
                return this.fechaSuneduField;
            }
            set
            {
                this.fechaSuneduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string horaSunedu
        {
            get
            {
                return this.horaSuneduField;
            }
            set
            {
                this.horaSuneduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cGenerico
        {
            get
            {
                return this.cGenericoField;
            }
            set
            {
                this.cGenericoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dGenerica
        {
            get
            {
                return this.dGenericaField;
            }
            set
            {
                this.dGenericaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/")]
    public partial class gradosTitulo
    {
        
        private string aPEMATField;
        
        private string aPEPATField;
        
        private string dOCU_NUMField;
        
        private string dOCU_TIPField;
        
        private string nIVELField;
        
        private string nOMBRESField;
        
        private string nOMBRE_IEField;
        
        private string nOMBRE_TITUField;
        
        private string nUM_TITUField;
        
        private string tITU_FECField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string APEMAT
        {
            get
            {
                return this.aPEMATField;
            }
            set
            {
                this.aPEMATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string APEPAT
        {
            get
            {
                return this.aPEPATField;
            }
            set
            {
                this.aPEPATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DOCU_NUM
        {
            get
            {
                return this.dOCU_NUMField;
            }
            set
            {
                this.dOCU_NUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DOCU_TIP
        {
            get
            {
                return this.dOCU_TIPField;
            }
            set
            {
                this.dOCU_TIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string NIVEL
        {
            get
            {
                return this.nIVELField;
            }
            set
            {
                this.nIVELField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string NOMBRES
        {
            get
            {
                return this.nOMBRESField;
            }
            set
            {
                this.nOMBRESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string NOMBRE_IE
        {
            get
            {
                return this.nOMBRE_IEField;
            }
            set
            {
                this.nOMBRE_IEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string NOMBRE_TITU
        {
            get
            {
                return this.nOMBRE_TITUField;
            }
            set
            {
                this.nOMBRE_TITUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string NUM_TITU
        {
            get
            {
                return this.nUM_TITUField;
            }
            set
            {
                this.nUM_TITUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string TITU_FEC
        {
            get
            {
                return this.tITU_FECField;
            }
            set
            {
                this.tITU_FECField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/")]
    public partial class datosPersona
    {
        
        private string apPrimerField;
        
        private string apSegundoField;
        
        private string direccionField;
        
        private string estadoCivilField;
        
        private byte[] fotoField;
        
        private string prenombresField;
        
        private string restriccionField;
        
        private string ubigeoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apPrimer
        {
            get
            {
                return this.apPrimerField;
            }
            set
            {
                this.apPrimerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apSegundo
        {
            get
            {
                return this.apSegundoField;
            }
            set
            {
                this.apSegundoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string estadoCivil
        {
            get
            {
                return this.estadoCivilField;
            }
            set
            {
                this.estadoCivilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] foto
        {
            get
            {
                return this.fotoField;
            }
            set
            {
                this.fotoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string prenombres
        {
            get
            {
                return this.prenombresField;
            }
            set
            {
                this.prenombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string restriccion
        {
            get
            {
                return this.restriccionField;
            }
            set
            {
                this.restriccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ubigeo
        {
            get
            {
                return this.ubigeoField;
            }
            set
            {
                this.ubigeoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/")]
    public partial class Afiliacion
    {
        
        private string coAfiliacionField;
        
        private string tiPlanSaludField;
        
        private string dePlanSaludField;
        
        private string coIafasField;
        
        private string tiIafasField;
        
        private string deIafasField;
        
        private string coParentescoField;
        
        private string coPaisTitularField;
        
        private string tiDocTitularField;
        
        private string nuDocTitularField;
        
        private string feIniAfiliacionField;
        
        private string feFinAfiliacionField;
        
        private string feFinCoberturaField;
        
        private string feActIafasField;
        
        private string feActSunasaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string coAfiliacion
        {
            get
            {
                return this.coAfiliacionField;
            }
            set
            {
                this.coAfiliacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tiPlanSalud
        {
            get
            {
                return this.tiPlanSaludField;
            }
            set
            {
                this.tiPlanSaludField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dePlanSalud
        {
            get
            {
                return this.dePlanSaludField;
            }
            set
            {
                this.dePlanSaludField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string coIafas
        {
            get
            {
                return this.coIafasField;
            }
            set
            {
                this.coIafasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string tiIafas
        {
            get
            {
                return this.tiIafasField;
            }
            set
            {
                this.tiIafasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string deIafas
        {
            get
            {
                return this.deIafasField;
            }
            set
            {
                this.deIafasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string coParentesco
        {
            get
            {
                return this.coParentescoField;
            }
            set
            {
                this.coParentescoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string coPaisTitular
        {
            get
            {
                return this.coPaisTitularField;
            }
            set
            {
                this.coPaisTitularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string tiDocTitular
        {
            get
            {
                return this.tiDocTitularField;
            }
            set
            {
                this.tiDocTitularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string nuDocTitular
        {
            get
            {
                return this.nuDocTitularField;
            }
            set
            {
                this.nuDocTitularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string feIniAfiliacion
        {
            get
            {
                return this.feIniAfiliacionField;
            }
            set
            {
                this.feIniAfiliacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string feFinAfiliacion
        {
            get
            {
                return this.feFinAfiliacionField;
            }
            set
            {
                this.feFinAfiliacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string feFinCobertura
        {
            get
            {
                return this.feFinCoberturaField;
            }
            set
            {
                this.feFinCoberturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string feActIafas
        {
            get
            {
                return this.feActIafasField;
            }
            set
            {
                this.feActIafasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string feActSunasa
        {
            get
            {
                return this.feActSunasaField;
            }
            set
            {
                this.feActSunasaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/")]
    public partial class pensionista
    {
        
        private string descripcionPensionistaField;
        
        private string regimenPensionistaField;
        
        private string leyPensionistaField;
        
        private string codigoPensionistaField;
        
        private string prestacionPensionistaField;
        
        private string fechaPensionistaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcionPensionista
        {
            get
            {
                return this.descripcionPensionistaField;
            }
            set
            {
                this.descripcionPensionistaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string regimenPensionista
        {
            get
            {
                return this.regimenPensionistaField;
            }
            set
            {
                this.regimenPensionistaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string leyPensionista
        {
            get
            {
                return this.leyPensionistaField;
            }
            set
            {
                this.leyPensionistaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codigoPensionista
        {
            get
            {
                return this.codigoPensionistaField;
            }
            set
            {
                this.codigoPensionistaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string prestacionPensionista
        {
            get
            {
                return this.prestacionPensionistaField;
            }
            set
            {
                this.prestacionPensionistaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fechaPensionista
        {
            get
            {
                return this.fechaPensionistaField;
            }
            set
            {
                this.fechaPensionistaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MigraciogetCarnetExt", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class MigraciogetCarnetExtRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDocumento;
        
        public MigraciogetCarnetExtRequest()
        {
        }
        
        public MigraciogetCarnetExtRequest(string numDocumento, string tipoDocumento)
        {
            this.numDocumento = numDocumento;
            this.tipoDocumento = tipoDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MigraciogetCarnetExtResponse", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class MigraciogetCarnetExtResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsSoapONGEI.CarnetExtranjeria CarnetExtranjeria;
        
        public MigraciogetCarnetExtResponse()
        {
        }
        
        public MigraciogetCarnetExtResponse(wsSoapONGEI.CarnetExtranjeria CarnetExtranjeria)
        {
            this.CarnetExtranjeria = CarnetExtranjeria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PJgetAntecPenales", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class PJgetAntecPenalesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoPaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoMaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string motivoConsulta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string procesoEntidadConsultante;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dniPersonaConsultante;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string audNombrePC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string audIP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string audNombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string audDireccionMAC;
        
        public PJgetAntecPenalesRequest()
        {
        }
        
        public PJgetAntecPenalesRequest(string apellidoPaterno, string apellidoMaterno, string nombre1, string nombre2, string nombre3, string dni, string motivoConsulta, string procesoEntidadConsultante, string dniPersonaConsultante, string audNombrePC, string audIP, string audNombreUsuario, string audDireccionMAC)
        {
            this.apellidoPaterno = apellidoPaterno;
            this.apellidoMaterno = apellidoMaterno;
            this.nombre1 = nombre1;
            this.nombre2 = nombre2;
            this.nombre3 = nombre3;
            this.dni = dni;
            this.motivoConsulta = motivoConsulta;
            this.procesoEntidadConsultante = procesoEntidadConsultante;
            this.dniPersonaConsultante = dniPersonaConsultante;
            this.audNombrePC = audNombrePC;
            this.audIP = audIP;
            this.audNombreUsuario = audNombreUsuario;
            this.audDireccionMAC = audDireccionMAC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PJgetAntecPenalesResponse", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class PJgetAntecPenalesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRespuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensajeRespuesta;
        
        public PJgetAntecPenalesResponse()
        {
        }
        
        public PJgetAntecPenalesResponse(string codigoRespuesta, string mensajeRespuesta)
        {
            this.codigoRespuesta = codigoRespuesta;
            this.mensajeRespuesta = mensajeRespuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ONPconsultarPensionista", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class ONPconsultarPensionistaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UsuarioEntidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ipConsulta;
        
        public ONPconsultarPensionistaRequest()
        {
        }
        
        public ONPconsultarPensionistaRequest(string tipoDocumento, string nDocumento, string UsuarioEntidad, string ipConsulta)
        {
            this.tipoDocumento = tipoDocumento;
            this.nDocumento = nDocumento;
            this.UsuarioEntidad = UsuarioEntidad;
            this.ipConsulta = ipConsulta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ONPconsultarPensionistaResponse", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class ONPconsultarPensionistaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRespuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionRespuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("pensionista", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsSoapONGEI.pensionista[] pensionista;
        
        public ONPconsultarPensionistaResponse()
        {
        }
        
        public ONPconsultarPensionistaResponse(string codigoRespuesta, string descripcionRespuesta, wsSoapONGEI.pensionista[] pensionista)
        {
            this.codigoRespuesta = codigoRespuesta;
            this.descripcionRespuesta = descripcionRespuesta;
            this.pensionista = pensionista;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SusaludConsulAfiliados", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class SusaludConsulAfiliadosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idInstitucion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tiDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nuDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string doConsultante;
        
        public SusaludConsulAfiliadosRequest()
        {
        }
        
        public SusaludConsulAfiliadosRequest(string idInstitucion, string tiDocumento, string nuDocumento, string doConsultante)
        {
            this.idInstitucion = idInstitucion;
            this.tiDocumento = tiDocumento;
            this.nuDocumento = nuDocumento;
            this.doConsultante = doConsultante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SusaludConsulAfiliadosResponse", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class SusaludConsulAfiliadosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coError;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tiDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nuDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apPaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apMaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apCasada;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string noPersona;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deSexo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string feNacimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deUbigeo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coContinente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deContinente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coPais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dePais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coDepartamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deDepartamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=16)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coProvincia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=17)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deProvincia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=18)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coDistrito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=19)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deDistrito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=20)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inFallecimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=21)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string feFallecimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=22)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coPaisEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=23)]
        [System.Xml.Serialization.XmlElementAttribute("Afiliaciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsSoapONGEI.Afiliacion[] Afiliaciones;
        
        public SusaludConsulAfiliadosResponse()
        {
        }
        
        public SusaludConsulAfiliadosResponse(
                    string coError, 
                    string tiDocumento, 
                    string nuDocumento, 
                    string apPaterno, 
                    string apMaterno, 
                    string apCasada, 
                    string noPersona, 
                    string deSexo, 
                    string feNacimiento, 
                    string deUbigeo, 
                    string coContinente, 
                    string deContinente, 
                    string coPais, 
                    string dePais, 
                    string coDepartamento, 
                    string deDepartamento, 
                    string coProvincia, 
                    string deProvincia, 
                    string coDistrito, 
                    string deDistrito, 
                    string inFallecimiento, 
                    string feFallecimiento, 
                    string coPaisEmisor, 
                    wsSoapONGEI.Afiliacion[] Afiliaciones)
        {
            this.coError = coError;
            this.tiDocumento = tiDocumento;
            this.nuDocumento = nuDocumento;
            this.apPaterno = apPaterno;
            this.apMaterno = apMaterno;
            this.apCasada = apCasada;
            this.noPersona = noPersona;
            this.deSexo = deSexo;
            this.feNacimiento = feNacimiento;
            this.deUbigeo = deUbigeo;
            this.coContinente = coContinente;
            this.deContinente = deContinente;
            this.coPais = coPais;
            this.dePais = dePais;
            this.coDepartamento = coDepartamento;
            this.deDepartamento = deDepartamento;
            this.coProvincia = coProvincia;
            this.deProvincia = deProvincia;
            this.coDistrito = coDistrito;
            this.deDistrito = deDistrito;
            this.inFallecimiento = inFallecimiento;
            this.feFallecimiento = feFallecimiento;
            this.coPaisEmisor = coPaisEmisor;
            this.Afiliaciones = Afiliaciones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReniecActuaCredencial", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class ReniecActuaCredencialRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string credencialAnterior;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string credencialNueva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nuDni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nuRuc;
        
        public ReniecActuaCredencialRequest()
        {
        }
        
        public ReniecActuaCredencialRequest(string credencialAnterior, string credencialNueva, string nuDni, string nuRuc)
        {
            this.credencialAnterior = credencialAnterior;
            this.credencialNueva = credencialNueva;
            this.nuDni = nuDni;
            this.nuRuc = nuRuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReniecActuaCredencialResponse", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class ReniecActuaCredencialResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coResultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deResultado;
        
        public ReniecActuaCredencialResponse()
        {
        }
        
        public ReniecActuaCredencialResponse(string coResultado, string deResultado)
        {
            this.coResultado = coResultado;
            this.deResultado = deResultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReniecConsultDni", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class ReniecConsultDniRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nuDniConsulta;
        
        public ReniecConsultDniRequest()
        {
        }
        
        public ReniecConsultDniRequest(string nuDniConsulta)
        {
            this.nuDniConsulta = nuDniConsulta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReniecConsultDniResponse", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class ReniecConsultDniResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string coResultado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsSoapONGEI.datosPersona datosPersona;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deResultado;
        
        public ReniecConsultDniResponse()
        {
        }
        
        public ReniecConsultDniResponse(string coResultado, wsSoapONGEI.datosPersona datosPersona, string deResultado)
        {
            this.coResultado = coResultado;
            this.datosPersona = datosPersona;
            this.deResultado = deResultado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MineduConsulTitulo", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class MineduConsulTituloRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nroDocumento;
        
        public MineduConsulTituloRequest()
        {
        }
        
        public MineduConsulTituloRequest(string nroDocumento)
        {
            this.nroDocumento = nroDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MineduConsulTituloResponse", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class MineduConsulTituloResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("gradosTitulo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsSoapONGEI.gradosTitulo[] gradosTitulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje;
        
        public MineduConsulTituloResponse()
        {
        }
        
        public MineduConsulTituloResponse(wsSoapONGEI.gradosTitulo[] gradosTitulo, string mensaje)
        {
            this.gradosTitulo = gradosTitulo;
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InpegetAntecedenteJudicial", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class InpegetAntecedenteJudicialRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apepat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apemat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        public InpegetAntecedenteJudicialRequest()
        {
        }
        
        public InpegetAntecedenteJudicialRequest(string apepat, string apemat, string nombres)
        {
            this.apepat = apepat;
            this.apemat = apemat;
            this.nombres = nombres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InpegetAntecedenteJudicialResponse", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class InpegetAntecedenteJudicialResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string antecedenteJudicial;
        
        public InpegetAntecedenteJudicialResponse()
        {
        }
        
        public InpegetAntecedenteJudicialResponse(string antecedenteJudicial)
        {
            this.antecedenteJudicial = antecedenteJudicial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SuneduConsulRNGT", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class SuneduConsulRNGTRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nroDocIdentidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ip_wsUser;
        
        public SuneduConsulRNGTRequest()
        {
        }
        
        public SuneduConsulRNGTRequest(string nroDocIdentidad, string ip_wsUser)
        {
            this.nroDocIdentidad = nroDocIdentidad;
            this.ip_wsUser = ip_wsUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SuneduConsulRNGTResponse", WrapperNamespace="http://mtc.gob.pe/ServiciosOngeiMTC/", IsWrapped=true)]
    public partial class SuneduConsulRNGTResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsSoapONGEI.respuesta respuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mtc.gob.pe/ServiciosOngeiMTC/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("persona", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsSoapONGEI.Persona[] persona;
        
        public SuneduConsulRNGTResponse()
        {
        }
        
        public SuneduConsulRNGTResponse(wsSoapONGEI.respuesta respuesta, wsSoapONGEI.Persona[] persona)
        {
            this.respuesta = respuesta;
            this.persona = persona;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface ServiciosOngeiMTCChannel : wsSoapONGEI.ServiciosOngeiMTC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class ServiciosOngeiMTCClient : System.ServiceModel.ClientBase<wsSoapONGEI.ServiciosOngeiMTC>, wsSoapONGEI.ServiciosOngeiMTC
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiciosOngeiMTCClient() : 
                base(ServiciosOngeiMTCClient.GetDefaultBinding(), ServiciosOngeiMTCClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServiciosOngeiMTCHTTPSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiciosOngeiMTCClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiciosOngeiMTCClient.GetBindingForEndpoint(endpointConfiguration), ServiciosOngeiMTCClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiciosOngeiMTCClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiciosOngeiMTCClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiciosOngeiMTCClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiciosOngeiMTCClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiciosOngeiMTCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<wsSoapONGEI.PCMEnviarSMSResponse> PCMEnviarSMSAsync(wsSoapONGEI.PCMEnviarSMSRequest request)
        {
            return base.Channel.PCMEnviarSMSAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSoapONGEI.MigraciogetCarnetExtResponse> wsSoapONGEI.ServiciosOngeiMTC.MigraciogetCarnetExtAsync(wsSoapONGEI.MigraciogetCarnetExtRequest request)
        {
            return base.Channel.MigraciogetCarnetExtAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsSoapONGEI.MigraciogetCarnetExtResponse> MigraciogetCarnetExtAsync(string numDocumento, string tipoDocumento)
        {
            wsSoapONGEI.MigraciogetCarnetExtRequest inValue = new wsSoapONGEI.MigraciogetCarnetExtRequest();
            inValue.numDocumento = numDocumento;
            inValue.tipoDocumento = tipoDocumento;
            return ((wsSoapONGEI.ServiciosOngeiMTC)(this)).MigraciogetCarnetExtAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<wsSoapONGEI.PJgetAntecPenalesResponse> PJgetAntecPenalesAsync(wsSoapONGEI.PJgetAntecPenalesRequest request)
        {
            return base.Channel.PJgetAntecPenalesAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsSoapONGEI.ONPconsultarPensionistaResponse> ONPconsultarPensionistaAsync(wsSoapONGEI.ONPconsultarPensionistaRequest request)
        {
            return base.Channel.ONPconsultarPensionistaAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsSoapONGEI.SusaludConsulAfiliadosResponse> SusaludConsulAfiliadosAsync(wsSoapONGEI.SusaludConsulAfiliadosRequest request)
        {
            return base.Channel.SusaludConsulAfiliadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsSoapONGEI.ReniecActuaCredencialResponse> ReniecActuaCredencialAsync(wsSoapONGEI.ReniecActuaCredencialRequest request)
        {
            return base.Channel.ReniecActuaCredencialAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsSoapONGEI.ReniecConsultDniResponse> ReniecConsultDniAsync(wsSoapONGEI.ReniecConsultDniRequest request)
        {
            return base.Channel.ReniecConsultDniAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsSoapONGEI.MineduConsulTituloResponse> MineduConsulTituloAsync(wsSoapONGEI.MineduConsulTituloRequest request)
        {
            return base.Channel.MineduConsulTituloAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsSoapONGEI.InpegetAntecedenteJudicialResponse> wsSoapONGEI.ServiciosOngeiMTC.InpegetAntecedenteJudicialAsync(wsSoapONGEI.InpegetAntecedenteJudicialRequest request)
        {
            return base.Channel.InpegetAntecedenteJudicialAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsSoapONGEI.InpegetAntecedenteJudicialResponse> InpegetAntecedenteJudicialAsync(string apepat, string apemat, string nombres)
        {
            wsSoapONGEI.InpegetAntecedenteJudicialRequest inValue = new wsSoapONGEI.InpegetAntecedenteJudicialRequest();
            inValue.apepat = apepat;
            inValue.apemat = apemat;
            inValue.nombres = nombres;
            return ((wsSoapONGEI.ServiciosOngeiMTC)(this)).InpegetAntecedenteJudicialAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<wsSoapONGEI.SuneduConsulRNGTResponse> SuneduConsulRNGTAsync(wsSoapONGEI.SuneduConsulRNGTRequest request)
        {
            return base.Channel.SuneduConsulRNGTAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiciosOngeiMTCHTTPSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiciosOngeiMTCHTTPSOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://mtc-presb01.mtc.gob.pe:7804/consultas/ongei/servicios");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiciosOngeiMTCClient.GetBindingForEndpoint(EndpointConfiguration.ServiciosOngeiMTCHTTPSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiciosOngeiMTCClient.GetEndpointAddress(EndpointConfiguration.ServiciosOngeiMTCHTTPSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            ServiciosOngeiMTCHTTPSOAP,
        }
    }
}
