//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsSoapSUNAT
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wwss.sunat.gob.pe/jboss-net/services/ConsultaRuc", ConfigurationName="wsSoapSUNAT.DatosRucWSFacadeRemote")]
    public interface DatosRucWSFacadeRemote
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="ConsultaRuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT362))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT1150))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanSpr))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanRso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getDatosPrincipalesReturn")]
        System.Threading.Tasks.Task<wsSoapSUNAT.BeanDdp> getDatosPrincipalesAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="ConsultaRuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT362))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT1150))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanSpr))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanRso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getDomicilioLegalReturn")]
        System.Threading.Tasks.Task<string> getDomicilioLegalAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="ConsultaRuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT362))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT1150))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanSpr))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanRso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getDatosT1144Return")]
        System.Threading.Tasks.Task<wsSoapSUNAT.BeanT1144> getDatosT1144Async(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="ConsultaRuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT362))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT1150))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanSpr))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanRso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getDatosSecundariosReturn")]
        System.Threading.Tasks.Task<wsSoapSUNAT.BeanDds> getDatosSecundariosAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="ConsultaRuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT362))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT1150))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanSpr))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanRso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getRepLegalesReturn")]
        System.Threading.Tasks.Task<wsSoapSUNAT.BeanRso[]> getRepLegalesAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="ConsultaRuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT362))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT1150))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanSpr))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanRso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getEstablecimientosAnexosReturn")]
        System.Threading.Tasks.Task<wsSoapSUNAT.BeanSpr[]> getEstablecimientosAnexosAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="ConsultaRuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT362))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT1150))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanSpr))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanRso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getEstAnexosT1150Return")]
        System.Threading.Tasks.Task<wsSoapSUNAT.BeanT1150[]> getEstAnexosT1150Async(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="ConsultaRuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT362))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT1150))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanSpr))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanRso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="buscaRazonSocialReturn")]
        System.Threading.Tasks.Task<wsSoapSUNAT.BeanDdp[]> buscaRazonSocialAsync(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="ConsultaRuc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT362))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanT1150))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanSpr))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BeanRso))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getDatosT362Return")]
        System.Threading.Tasks.Task<wsSoapSUNAT.BeanT362[]> getDatosT362Async(string in0);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ConsultaRuc")]
    public partial class BeanDdp
    {
        
        private string cod_depField;
        
        private string cod_distField;
        
        private string cod_provField;
        
        private string ddp_ciiuField;
        
        private string ddp_dobleField;
        
        private string ddp_estadoField;
        
        private string ddp_fecactField;
        
        private string ddp_fecaltField;
        
        private string ddp_fecbajField;
        
        private string ddp_flag22Field;
        
        private string ddp_identiField;
        
        private string ddp_inter1Field;
        
        private string ddp_llltttField;
        
        private string ddp_mclaseField;
        
        private string ddp_nombreField;
        
        private string ddp_nomviaField;
        
        private string ddp_nomzonField;
        
        private string ddp_numer1Field;
        
        private string ddp_numregField;
        
        private string ddp_numrucField;
        
        private string ddp_reactiField;
        
        private string ddp_refer1Field;
        
        private int ddp_secuenField;
        
        private string ddp_tamanoField;
        
        private string ddp_tipviaField;
        
        private string ddp_tipzonField;
        
        private string ddp_tpoempField;
        
        private string ddp_ubigeoField;
        
        private string ddp_usernaField;
        
        private string desc_ciiuField;
        
        private string desc_depField;
        
        private string desc_distField;
        
        private string desc_estadoField;
        
        private string desc_flag22Field;
        
        private string desc_identiField;
        
        private string desc_numregField;
        
        private string desc_provField;
        
        private string desc_tamanoField;
        
        private string desc_tipviaField;
        
        private string desc_tipzonField;
        
        private string desc_tpoempField;
        
        private bool esActivoField;
        
        private bool esHabidoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_dep
        {
            get
            {
                return this.cod_depField;
            }
            set
            {
                this.cod_depField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_dist
        {
            get
            {
                return this.cod_distField;
            }
            set
            {
                this.cod_distField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_prov
        {
            get
            {
                return this.cod_provField;
            }
            set
            {
                this.cod_provField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_ciiu
        {
            get
            {
                return this.ddp_ciiuField;
            }
            set
            {
                this.ddp_ciiuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_doble
        {
            get
            {
                return this.ddp_dobleField;
            }
            set
            {
                this.ddp_dobleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_estado
        {
            get
            {
                return this.ddp_estadoField;
            }
            set
            {
                this.ddp_estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_fecact
        {
            get
            {
                return this.ddp_fecactField;
            }
            set
            {
                this.ddp_fecactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_fecalt
        {
            get
            {
                return this.ddp_fecaltField;
            }
            set
            {
                this.ddp_fecaltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_fecbaj
        {
            get
            {
                return this.ddp_fecbajField;
            }
            set
            {
                this.ddp_fecbajField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_flag22
        {
            get
            {
                return this.ddp_flag22Field;
            }
            set
            {
                this.ddp_flag22Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_identi
        {
            get
            {
                return this.ddp_identiField;
            }
            set
            {
                this.ddp_identiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_inter1
        {
            get
            {
                return this.ddp_inter1Field;
            }
            set
            {
                this.ddp_inter1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_lllttt
        {
            get
            {
                return this.ddp_llltttField;
            }
            set
            {
                this.ddp_llltttField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_mclase
        {
            get
            {
                return this.ddp_mclaseField;
            }
            set
            {
                this.ddp_mclaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_nombre
        {
            get
            {
                return this.ddp_nombreField;
            }
            set
            {
                this.ddp_nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_nomvia
        {
            get
            {
                return this.ddp_nomviaField;
            }
            set
            {
                this.ddp_nomviaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_nomzon
        {
            get
            {
                return this.ddp_nomzonField;
            }
            set
            {
                this.ddp_nomzonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_numer1
        {
            get
            {
                return this.ddp_numer1Field;
            }
            set
            {
                this.ddp_numer1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_numreg
        {
            get
            {
                return this.ddp_numregField;
            }
            set
            {
                this.ddp_numregField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_numruc
        {
            get
            {
                return this.ddp_numrucField;
            }
            set
            {
                this.ddp_numrucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_reacti
        {
            get
            {
                return this.ddp_reactiField;
            }
            set
            {
                this.ddp_reactiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_refer1
        {
            get
            {
                return this.ddp_refer1Field;
            }
            set
            {
                this.ddp_refer1Field = value;
            }
        }
        
        /// <remarks/>
        public int ddp_secuen
        {
            get
            {
                return this.ddp_secuenField;
            }
            set
            {
                this.ddp_secuenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_tamano
        {
            get
            {
                return this.ddp_tamanoField;
            }
            set
            {
                this.ddp_tamanoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_tipvia
        {
            get
            {
                return this.ddp_tipviaField;
            }
            set
            {
                this.ddp_tipviaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_tipzon
        {
            get
            {
                return this.ddp_tipzonField;
            }
            set
            {
                this.ddp_tipzonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_tpoemp
        {
            get
            {
                return this.ddp_tpoempField;
            }
            set
            {
                this.ddp_tpoempField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_ubigeo
        {
            get
            {
                return this.ddp_ubigeoField;
            }
            set
            {
                this.ddp_ubigeoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddp_userna
        {
            get
            {
                return this.ddp_usernaField;
            }
            set
            {
                this.ddp_usernaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_ciiu
        {
            get
            {
                return this.desc_ciiuField;
            }
            set
            {
                this.desc_ciiuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_dep
        {
            get
            {
                return this.desc_depField;
            }
            set
            {
                this.desc_depField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_dist
        {
            get
            {
                return this.desc_distField;
            }
            set
            {
                this.desc_distField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_estado
        {
            get
            {
                return this.desc_estadoField;
            }
            set
            {
                this.desc_estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_flag22
        {
            get
            {
                return this.desc_flag22Field;
            }
            set
            {
                this.desc_flag22Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_identi
        {
            get
            {
                return this.desc_identiField;
            }
            set
            {
                this.desc_identiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_numreg
        {
            get
            {
                return this.desc_numregField;
            }
            set
            {
                this.desc_numregField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_prov
        {
            get
            {
                return this.desc_provField;
            }
            set
            {
                this.desc_provField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_tamano
        {
            get
            {
                return this.desc_tamanoField;
            }
            set
            {
                this.desc_tamanoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_tipvia
        {
            get
            {
                return this.desc_tipviaField;
            }
            set
            {
                this.desc_tipviaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_tipzon
        {
            get
            {
                return this.desc_tipzonField;
            }
            set
            {
                this.desc_tipzonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_tpoemp
        {
            get
            {
                return this.desc_tpoempField;
            }
            set
            {
                this.desc_tpoempField = value;
            }
        }
        
        /// <remarks/>
        public bool esActivo
        {
            get
            {
                return this.esActivoField;
            }
            set
            {
                this.esActivoField = value;
            }
        }
        
        /// <remarks/>
        public bool esHabido
        {
            get
            {
                return this.esHabidoField;
            }
            set
            {
                this.esHabidoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ConsultaRuc")]
    public partial class BeanT362
    {
        
        private string desc_numregField;
        
        private string t362_fecactField;
        
        private string t362_fecbajField;
        
        private int t362_indiceField;
        
        private string t362_nombreField;
        
        private string t362_numregField;
        
        private string t362_numrucField;
        
        private string t362_usernaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_numreg
        {
            get
            {
                return this.desc_numregField;
            }
            set
            {
                this.desc_numregField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string t362_fecact
        {
            get
            {
                return this.t362_fecactField;
            }
            set
            {
                this.t362_fecactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string t362_fecbaj
        {
            get
            {
                return this.t362_fecbajField;
            }
            set
            {
                this.t362_fecbajField = value;
            }
        }
        
        /// <remarks/>
        public int t362_indice
        {
            get
            {
                return this.t362_indiceField;
            }
            set
            {
                this.t362_indiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string t362_nombre
        {
            get
            {
                return this.t362_nombreField;
            }
            set
            {
                this.t362_nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string t362_numreg
        {
            get
            {
                return this.t362_numregField;
            }
            set
            {
                this.t362_numregField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string t362_numruc
        {
            get
            {
                return this.t362_numrucField;
            }
            set
            {
                this.t362_numrucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string t362_userna
        {
            get
            {
                return this.t362_usernaField;
            }
            set
            {
                this.t362_usernaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ConsultaRuc")]
    public partial class BeanT1150
    {
        
        private string cod_usernaField;
        
        private string fec_actField;
        
        private string ind_conlegField;
        
        private short num_correlField;
        
        private string num_deparField;
        
        private string num_kilomField;
        
        private string num_loteField;
        
        private string num_manzaField;
        
        private string num_rucField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_userna
        {
            get
            {
                return this.cod_usernaField;
            }
            set
            {
                this.cod_usernaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fec_act
        {
            get
            {
                return this.fec_actField;
            }
            set
            {
                this.fec_actField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ind_conleg
        {
            get
            {
                return this.ind_conlegField;
            }
            set
            {
                this.ind_conlegField = value;
            }
        }
        
        /// <remarks/>
        public short num_correl
        {
            get
            {
                return this.num_correlField;
            }
            set
            {
                this.num_correlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string num_depar
        {
            get
            {
                return this.num_deparField;
            }
            set
            {
                this.num_deparField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string num_kilom
        {
            get
            {
                return this.num_kilomField;
            }
            set
            {
                this.num_kilomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string num_lote
        {
            get
            {
                return this.num_loteField;
            }
            set
            {
                this.num_loteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string num_manza
        {
            get
            {
                return this.num_manzaField;
            }
            set
            {
                this.num_manzaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string num_ruc
        {
            get
            {
                return this.num_rucField;
            }
            set
            {
                this.num_rucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ConsultaRuc")]
    public partial class BeanSpr
    {
        
        private string cod_depField;
        
        private string cod_distField;
        
        private string cod_provField;
        
        private string desc_depField;
        
        private string desc_distField;
        
        private string desc_provField;
        
        private string desc_tipestField;
        
        private string desc_tipviaField;
        
        private string desc_tipzonField;
        
        private string direccionField;
        
        private int spr_correlField;
        
        private string spr_fecactField;
        
        private string spr_inter1Field;
        
        private string spr_licencField;
        
        private string spr_nombreField;
        
        private string spr_nomviaField;
        
        private string spr_nomzonField;
        
        private string spr_numer1Field;
        
        private string spr_numrucField;
        
        private string spr_refer1Field;
        
        private string spr_tipestField;
        
        private string spr_tipviaField;
        
        private string spr_tipzonField;
        
        private string spr_ubigeoField;
        
        private string spr_usernaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_dep
        {
            get
            {
                return this.cod_depField;
            }
            set
            {
                this.cod_depField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_dist
        {
            get
            {
                return this.cod_distField;
            }
            set
            {
                this.cod_distField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_prov
        {
            get
            {
                return this.cod_provField;
            }
            set
            {
                this.cod_provField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_dep
        {
            get
            {
                return this.desc_depField;
            }
            set
            {
                this.desc_depField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_dist
        {
            get
            {
                return this.desc_distField;
            }
            set
            {
                this.desc_distField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_prov
        {
            get
            {
                return this.desc_provField;
            }
            set
            {
                this.desc_provField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_tipest
        {
            get
            {
                return this.desc_tipestField;
            }
            set
            {
                this.desc_tipestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_tipvia
        {
            get
            {
                return this.desc_tipviaField;
            }
            set
            {
                this.desc_tipviaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_tipzon
        {
            get
            {
                return this.desc_tipzonField;
            }
            set
            {
                this.desc_tipzonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public int spr_correl
        {
            get
            {
                return this.spr_correlField;
            }
            set
            {
                this.spr_correlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string spr_fecact
        {
            get
            {
                return this.spr_fecactField;
            }
            set
            {
                this.spr_fecactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string spr_inter1
        {
            get
            {
                return this.spr_inter1Field;
            }
            set
            {
                this.spr_inter1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string spr_licenc
        {
            get
            {
                return this.spr_licencField;
            }
            set
            {
                this.spr_licencField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string spr_nombre
        {
            get
            {
                return this.spr_nombreField;
            }
            set
            {
                this.spr_nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string spr_nomvia
        {
            get
            {
                return this.spr_nomviaField;
            }
            set
            {
                this.spr_nomviaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string spr_nomzon
        {
            get
            {
                return this.spr_nomzonField;
            }
            set
            {
                this.spr_nomzonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string spr_numer1
        {
            get
            {
                return this.spr_numer1Field;
            }
            set
            {
                this.spr_numer1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string spr_numruc
        {
            get
            {
                return this.spr_numrucField;
            }
            set
            {
                this.spr_numrucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string spr_refer1
        {
            get
            {
                return this.spr_refer1Field;
            }
            set
            {
                this.spr_refer1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string spr_tipest
        {
            get
            {
                return this.spr_tipestField;
            }
            set
            {
                this.spr_tipestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string spr_tipvia
        {
            get
            {
                return this.spr_tipviaField;
            }
            set
            {
                this.spr_tipviaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string spr_tipzon
        {
            get
            {
                return this.spr_tipzonField;
            }
            set
            {
                this.spr_tipzonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string spr_ubigeo
        {
            get
            {
                return this.spr_ubigeoField;
            }
            set
            {
                this.spr_ubigeoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string spr_userna
        {
            get
            {
                return this.spr_usernaField;
            }
            set
            {
                this.spr_usernaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ConsultaRuc")]
    public partial class BeanRso
    {
        
        private string cod_cargoField;
        
        private string cod_deparField;
        
        private string desc_docideField;
        
        private short num_ord_suceField;
        
        private string rso_cargooField;
        
        private string rso_docideField;
        
        private string rso_fecactField;
        
        private string rso_fecnacField;
        
        private string rso_nombreField;
        
        private string rso_nrodocField;
        
        private string rso_numrucField;
        
        private string rso_usernaField;
        
        private string rso_vdesdeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_cargo
        {
            get
            {
                return this.cod_cargoField;
            }
            set
            {
                this.cod_cargoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_depar
        {
            get
            {
                return this.cod_deparField;
            }
            set
            {
                this.cod_deparField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_docide
        {
            get
            {
                return this.desc_docideField;
            }
            set
            {
                this.desc_docideField = value;
            }
        }
        
        /// <remarks/>
        public short num_ord_suce
        {
            get
            {
                return this.num_ord_suceField;
            }
            set
            {
                this.num_ord_suceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rso_cargoo
        {
            get
            {
                return this.rso_cargooField;
            }
            set
            {
                this.rso_cargooField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rso_docide
        {
            get
            {
                return this.rso_docideField;
            }
            set
            {
                this.rso_docideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rso_fecact
        {
            get
            {
                return this.rso_fecactField;
            }
            set
            {
                this.rso_fecactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rso_fecnac
        {
            get
            {
                return this.rso_fecnacField;
            }
            set
            {
                this.rso_fecnacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rso_nombre
        {
            get
            {
                return this.rso_nombreField;
            }
            set
            {
                this.rso_nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rso_nrodoc
        {
            get
            {
                return this.rso_nrodocField;
            }
            set
            {
                this.rso_nrodocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rso_numruc
        {
            get
            {
                return this.rso_numrucField;
            }
            set
            {
                this.rso_numrucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rso_userna
        {
            get
            {
                return this.rso_usernaField;
            }
            set
            {
                this.rso_usernaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rso_vdesde
        {
            get
            {
                return this.rso_vdesdeField;
            }
            set
            {
                this.rso_vdesdeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ConsultaRuc")]
    public partial class BeanDds
    {
        
        private string dds_apartaField;
        
        private string dds_asientField;
        
        private string dds_califiField;
        
        private string dds_centroField;
        
        private string dds_cierreField;
        
        private string dds_comextField;
        
        private string dds_constiField;
        
        private string dds_contabField;
        
        private string dds_docideField;
        
        private string dds_domiciField;
        
        private string dds_ejemplField;
        
        private string dds_facturField;
        
        private string dds_fecactField;
        
        private string dds_fecnacField;
        
        private string dds_fecvenField;
        
        private string dds_fichaField;
        
        private string dds_inicioField;
        
        private string dds_licencField;
        
        private string dds_motbajField;
        
        private string dds_motemiField;
        
        private string dds_nacionField;
        
        private string dds_nfolioField;
        
        private string dds_nomcomField;
        
        private string dds_nrodocField;
        
        private string dds_numfaxField;
        
        private string dds_numrucField;
        
        private string dds_orientField;
        
        private string dds_paispaField;
        
        private string dds_pasapoField;
        
        private string dds_patronField;
        
        private string dds_sexoField;
        
        private string dds_telef1Field;
        
        private string dds_telef2Field;
        
        private string dds_telef3Field;
        
        private string dds_usernaField;
        
        private string declaraField;
        
        private string desc_cierreField;
        
        private string desc_comextField;
        
        private string desc_contabField;
        
        private string desc_docideField;
        
        private string desc_domiciField;
        
        private string desc_facturField;
        
        private string desc_motbajField;
        
        private string desc_nacionField;
        
        private string desc_orientField;
        
        private string desc_sexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_aparta
        {
            get
            {
                return this.dds_apartaField;
            }
            set
            {
                this.dds_apartaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_asient
        {
            get
            {
                return this.dds_asientField;
            }
            set
            {
                this.dds_asientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_califi
        {
            get
            {
                return this.dds_califiField;
            }
            set
            {
                this.dds_califiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_centro
        {
            get
            {
                return this.dds_centroField;
            }
            set
            {
                this.dds_centroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_cierre
        {
            get
            {
                return this.dds_cierreField;
            }
            set
            {
                this.dds_cierreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_comext
        {
            get
            {
                return this.dds_comextField;
            }
            set
            {
                this.dds_comextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_consti
        {
            get
            {
                return this.dds_constiField;
            }
            set
            {
                this.dds_constiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_contab
        {
            get
            {
                return this.dds_contabField;
            }
            set
            {
                this.dds_contabField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_docide
        {
            get
            {
                return this.dds_docideField;
            }
            set
            {
                this.dds_docideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_domici
        {
            get
            {
                return this.dds_domiciField;
            }
            set
            {
                this.dds_domiciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_ejempl
        {
            get
            {
                return this.dds_ejemplField;
            }
            set
            {
                this.dds_ejemplField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_factur
        {
            get
            {
                return this.dds_facturField;
            }
            set
            {
                this.dds_facturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_fecact
        {
            get
            {
                return this.dds_fecactField;
            }
            set
            {
                this.dds_fecactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_fecnac
        {
            get
            {
                return this.dds_fecnacField;
            }
            set
            {
                this.dds_fecnacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_fecven
        {
            get
            {
                return this.dds_fecvenField;
            }
            set
            {
                this.dds_fecvenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_ficha
        {
            get
            {
                return this.dds_fichaField;
            }
            set
            {
                this.dds_fichaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_inicio
        {
            get
            {
                return this.dds_inicioField;
            }
            set
            {
                this.dds_inicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_licenc
        {
            get
            {
                return this.dds_licencField;
            }
            set
            {
                this.dds_licencField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_motbaj
        {
            get
            {
                return this.dds_motbajField;
            }
            set
            {
                this.dds_motbajField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_motemi
        {
            get
            {
                return this.dds_motemiField;
            }
            set
            {
                this.dds_motemiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_nacion
        {
            get
            {
                return this.dds_nacionField;
            }
            set
            {
                this.dds_nacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_nfolio
        {
            get
            {
                return this.dds_nfolioField;
            }
            set
            {
                this.dds_nfolioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_nomcom
        {
            get
            {
                return this.dds_nomcomField;
            }
            set
            {
                this.dds_nomcomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_nrodoc
        {
            get
            {
                return this.dds_nrodocField;
            }
            set
            {
                this.dds_nrodocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_numfax
        {
            get
            {
                return this.dds_numfaxField;
            }
            set
            {
                this.dds_numfaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_numruc
        {
            get
            {
                return this.dds_numrucField;
            }
            set
            {
                this.dds_numrucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_orient
        {
            get
            {
                return this.dds_orientField;
            }
            set
            {
                this.dds_orientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_paispa
        {
            get
            {
                return this.dds_paispaField;
            }
            set
            {
                this.dds_paispaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_pasapo
        {
            get
            {
                return this.dds_pasapoField;
            }
            set
            {
                this.dds_pasapoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_patron
        {
            get
            {
                return this.dds_patronField;
            }
            set
            {
                this.dds_patronField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_sexo
        {
            get
            {
                return this.dds_sexoField;
            }
            set
            {
                this.dds_sexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_telef1
        {
            get
            {
                return this.dds_telef1Field;
            }
            set
            {
                this.dds_telef1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_telef2
        {
            get
            {
                return this.dds_telef2Field;
            }
            set
            {
                this.dds_telef2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_telef3
        {
            get
            {
                return this.dds_telef3Field;
            }
            set
            {
                this.dds_telef3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dds_userna
        {
            get
            {
                return this.dds_usernaField;
            }
            set
            {
                this.dds_usernaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string declara
        {
            get
            {
                return this.declaraField;
            }
            set
            {
                this.declaraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_cierre
        {
            get
            {
                return this.desc_cierreField;
            }
            set
            {
                this.desc_cierreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_comext
        {
            get
            {
                return this.desc_comextField;
            }
            set
            {
                this.desc_comextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_contab
        {
            get
            {
                return this.desc_contabField;
            }
            set
            {
                this.desc_contabField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_docide
        {
            get
            {
                return this.desc_docideField;
            }
            set
            {
                this.desc_docideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_domici
        {
            get
            {
                return this.desc_domiciField;
            }
            set
            {
                this.desc_domiciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_factur
        {
            get
            {
                return this.desc_facturField;
            }
            set
            {
                this.desc_facturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_motbaj
        {
            get
            {
                return this.desc_motbajField;
            }
            set
            {
                this.desc_motbajField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_nacion
        {
            get
            {
                return this.desc_nacionField;
            }
            set
            {
                this.desc_nacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_orient
        {
            get
            {
                return this.desc_orientField;
            }
            set
            {
                this.desc_orientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string desc_sexo
        {
            get
            {
                return this.desc_sexoField;
            }
            set
            {
                this.desc_sexoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ConsultaRuc")]
    public partial class BeanT1144
    {
        
        private string cod_ciiu2Field;
        
        private string cod_ciiu3Field;
        
        private string cod_correo1Field;
        
        private string cod_correo2Field;
        
        private string cod_depar1Field;
        
        private string cod_depar2Field;
        
        private string cod_depar3Field;
        
        private string cod_depar4Field;
        
        private string cod_depar5Field;
        
        private string cod_paicapField;
        
        private string cod_paioriField;
        
        private string cod_usernaField;
        
        private string des_asientoField;
        
        private string des_ciiu2Field;
        
        private string des_ciiu3Field;
        
        private string des_conlegField;
        
        private string des_depar1Field;
        
        private string des_depar2Field;
        
        private string des_depar3Field;
        
        private string des_depar4Field;
        
        private string des_depar5Field;
        
        private string des_parregField;
        
        private string des_proindField;
        
        private string des_refnotField;
        
        private string fec_actField;
        
        private string fec_confir1Field;
        
        private string fec_confir2Field;
        
        private string ind_conlegField;
        
        private string ind_correo1Field;
        
        private string ind_correo2Field;
        
        private string ind_notifiField;
        
        private string ind_proindField;
        
        private string num_deparField;
        
        private string num_faxField;
        
        private string num_kilomField;
        
        private string num_loteField;
        
        private string num_manzaField;
        
        private string num_rucField;
        
        private string num_telef1Field;
        
        private string num_telef2Field;
        
        private string num_telef3Field;
        
        private string num_telef4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_ciiu2
        {
            get
            {
                return this.cod_ciiu2Field;
            }
            set
            {
                this.cod_ciiu2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_ciiu3
        {
            get
            {
                return this.cod_ciiu3Field;
            }
            set
            {
                this.cod_ciiu3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_correo1
        {
            get
            {
                return this.cod_correo1Field;
            }
            set
            {
                this.cod_correo1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_correo2
        {
            get
            {
                return this.cod_correo2Field;
            }
            set
            {
                this.cod_correo2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_depar1
        {
            get
            {
                return this.cod_depar1Field;
            }
            set
            {
                this.cod_depar1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_depar2
        {
            get
            {
                return this.cod_depar2Field;
            }
            set
            {
                this.cod_depar2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_depar3
        {
            get
            {
                return this.cod_depar3Field;
            }
            set
            {
                this.cod_depar3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_depar4
        {
            get
            {
                return this.cod_depar4Field;
            }
            set
            {
                this.cod_depar4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_depar5
        {
            get
            {
                return this.cod_depar5Field;
            }
            set
            {
                this.cod_depar5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_paicap
        {
            get
            {
                return this.cod_paicapField;
            }
            set
            {
                this.cod_paicapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_paiori
        {
            get
            {
                return this.cod_paioriField;
            }
            set
            {
                this.cod_paioriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cod_userna
        {
            get
            {
                return this.cod_usernaField;
            }
            set
            {
                this.cod_usernaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string des_asiento
        {
            get
            {
                return this.des_asientoField;
            }
            set
            {
                this.des_asientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string des_ciiu2
        {
            get
            {
                return this.des_ciiu2Field;
            }
            set
            {
                this.des_ciiu2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string des_ciiu3
        {
            get
            {
                return this.des_ciiu3Field;
            }
            set
            {
                this.des_ciiu3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string des_conleg
        {
            get
            {
                return this.des_conlegField;
            }
            set
            {
                this.des_conlegField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string des_depar1
        {
            get
            {
                return this.des_depar1Field;
            }
            set
            {
                this.des_depar1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string des_depar2
        {
            get
            {
                return this.des_depar2Field;
            }
            set
            {
                this.des_depar2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string des_depar3
        {
            get
            {
                return this.des_depar3Field;
            }
            set
            {
                this.des_depar3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string des_depar4
        {
            get
            {
                return this.des_depar4Field;
            }
            set
            {
                this.des_depar4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string des_depar5
        {
            get
            {
                return this.des_depar5Field;
            }
            set
            {
                this.des_depar5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string des_parreg
        {
            get
            {
                return this.des_parregField;
            }
            set
            {
                this.des_parregField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string des_proind
        {
            get
            {
                return this.des_proindField;
            }
            set
            {
                this.des_proindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string des_refnot
        {
            get
            {
                return this.des_refnotField;
            }
            set
            {
                this.des_refnotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fec_act
        {
            get
            {
                return this.fec_actField;
            }
            set
            {
                this.fec_actField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fec_confir1
        {
            get
            {
                return this.fec_confir1Field;
            }
            set
            {
                this.fec_confir1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fec_confir2
        {
            get
            {
                return this.fec_confir2Field;
            }
            set
            {
                this.fec_confir2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ind_conleg
        {
            get
            {
                return this.ind_conlegField;
            }
            set
            {
                this.ind_conlegField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ind_correo1
        {
            get
            {
                return this.ind_correo1Field;
            }
            set
            {
                this.ind_correo1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ind_correo2
        {
            get
            {
                return this.ind_correo2Field;
            }
            set
            {
                this.ind_correo2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ind_notifi
        {
            get
            {
                return this.ind_notifiField;
            }
            set
            {
                this.ind_notifiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ind_proind
        {
            get
            {
                return this.ind_proindField;
            }
            set
            {
                this.ind_proindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string num_depar
        {
            get
            {
                return this.num_deparField;
            }
            set
            {
                this.num_deparField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string num_fax
        {
            get
            {
                return this.num_faxField;
            }
            set
            {
                this.num_faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string num_kilom
        {
            get
            {
                return this.num_kilomField;
            }
            set
            {
                this.num_kilomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string num_lote
        {
            get
            {
                return this.num_loteField;
            }
            set
            {
                this.num_loteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string num_manza
        {
            get
            {
                return this.num_manzaField;
            }
            set
            {
                this.num_manzaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string num_ruc
        {
            get
            {
                return this.num_rucField;
            }
            set
            {
                this.num_rucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string num_telef1
        {
            get
            {
                return this.num_telef1Field;
            }
            set
            {
                this.num_telef1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string num_telef2
        {
            get
            {
                return this.num_telef2Field;
            }
            set
            {
                this.num_telef2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string num_telef3
        {
            get
            {
                return this.num_telef3Field;
            }
            set
            {
                this.num_telef3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string num_telef4
        {
            get
            {
                return this.num_telef4Field;
            }
            set
            {
                this.num_telef4Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface DatosRucWSFacadeRemoteChannel : wsSoapSUNAT.DatosRucWSFacadeRemote, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class DatosRucWSFacadeRemoteClient : System.ServiceModel.ClientBase<wsSoapSUNAT.DatosRucWSFacadeRemote>, wsSoapSUNAT.DatosRucWSFacadeRemote
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DatosRucWSFacadeRemoteClient() : 
                base(DatosRucWSFacadeRemoteClient.GetDefaultBinding(), DatosRucWSFacadeRemoteClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ConsultaRuc.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DatosRucWSFacadeRemoteClient(EndpointConfiguration endpointConfiguration) : 
                base(DatosRucWSFacadeRemoteClient.GetBindingForEndpoint(endpointConfiguration), DatosRucWSFacadeRemoteClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DatosRucWSFacadeRemoteClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DatosRucWSFacadeRemoteClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DatosRucWSFacadeRemoteClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DatosRucWSFacadeRemoteClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DatosRucWSFacadeRemoteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<wsSoapSUNAT.BeanDdp> getDatosPrincipalesAsync(string in0)
        {
            return base.Channel.getDatosPrincipalesAsync(in0);
        }
        
        public System.Threading.Tasks.Task<string> getDomicilioLegalAsync(string in0)
        {
            return base.Channel.getDomicilioLegalAsync(in0);
        }
        
        public System.Threading.Tasks.Task<wsSoapSUNAT.BeanT1144> getDatosT1144Async(string in0)
        {
            return base.Channel.getDatosT1144Async(in0);
        }
        
        public System.Threading.Tasks.Task<wsSoapSUNAT.BeanDds> getDatosSecundariosAsync(string in0)
        {
            return base.Channel.getDatosSecundariosAsync(in0);
        }
        
        public System.Threading.Tasks.Task<wsSoapSUNAT.BeanRso[]> getRepLegalesAsync(string in0)
        {
            return base.Channel.getRepLegalesAsync(in0);
        }
        
        public System.Threading.Tasks.Task<wsSoapSUNAT.BeanSpr[]> getEstablecimientosAnexosAsync(string in0)
        {
            return base.Channel.getEstablecimientosAnexosAsync(in0);
        }
        
        public System.Threading.Tasks.Task<wsSoapSUNAT.BeanT1150[]> getEstAnexosT1150Async(string in0)
        {
            return base.Channel.getEstAnexosT1150Async(in0);
        }
        
        public System.Threading.Tasks.Task<wsSoapSUNAT.BeanDdp[]> buscaRazonSocialAsync(string in0)
        {
            return base.Channel.buscaRazonSocialAsync(in0);
        }
        
        public System.Threading.Tasks.Task<wsSoapSUNAT.BeanT362[]> getDatosT362Async(string in0)
        {
            return base.Channel.getDatosT362Async(in0);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ConsultaRuc))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ConsultaRuc))
            {
                return new System.ServiceModel.EndpointAddress("http://wwss.sunat.gob.pe/jboss-net/services/ConsultaRuc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DatosRucWSFacadeRemoteClient.GetBindingForEndpoint(EndpointConfiguration.ConsultaRuc);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DatosRucWSFacadeRemoteClient.GetEndpointAddress(EndpointConfiguration.ConsultaRuc);
        }
        
        public enum EndpointConfiguration
        {
            
            ConsultaRuc,
        }
    }
}
